### ISSUE TITLE
Run out of VRAM: "vkAllocateMemory failed -1"

### ISSUE THREAD

**Issue by tanyiok1234** [nihui/waifu2x-ncnn-vulkan#1]
Thanks for your great job! It's super fast!

"vkAllocateMemory failed -1" happens when I try to convert from 1956x1956 with (Noise 2, Scale2).

Since converting from 978x978 to 1956x1956 (Noise 2, Scale 2) occupies 3.6G VRAM, I think it is reasonable to consider split photos into multiply slices (Like what they did in waifu2x-caffe).

By the way, I think 4G VRAM is an good target for memory usage control. Because most laptop usually equipped with 8G RAM and half of them could be used by Intel's graphic cards. (Since Nivida graphic card may choose cudnn and AMD usually has large VRAM, Intel is an good baseline)

**Comment by nihui** [comment]
thanks for your advice :)

**Comment by nihui** [comment]
hi, the new tiling scheme is now implemented
new bianry package is uploaded
