### ISSUE TITLE
Defects along the spliting edge

### ISSUE THREAD

**Issue by tanyiok1234** [nihui/waifu2x-ncnn-vulkan#10]
During the practice, I noticed that sometimes there are defects along the spliting edge, as shown here:
![image](https://user-images.githubusercontent.com/11721926/56208747-d236b780-608c-11e9-94a9-318588091983.png)

May be this is caused by the CUnet [results changes with blocks size]. Therefore, maybe techniques like blending should be considered. For example, overlapping several pixels at the edge and blend it with some weight.

May be it could be something like this:
X-axis (increases from left to right):  
Weight of Block A[390:400]: [1,    0.9,   0.8,   0.7........0.1]
Weight of Block B[0:10]:       [0.1,  0.2,   0.3,................1   ]
RGB_Out = RGB_A x Weight_A + RGB_B x Weight_B

Anyway, I am not sure whether this one would works or not. Maybe advanced curve like the Parabola one would be better. But I guess it would works and may applies to future model updates.

(PS: In stead of weighted blending, I think there are other approachs:
Use larger block and corp edge (Assume difference only happens at the edge)
Supervised Blending, which compares the pictures with original one and get something like penalty (Maybe not stable enough of source is noisy.

Thanks for your excellent work!
Best regards,

**Comment by nihui** [comment]
hi, please provide me this original image and the command line option you use

**Comment by tanyiok1234** [comment]
![2](https://user-images.githubusercontent.com/11721926/56269169-0f9f5180-612e-11e9-960e-ec3e1086bb4f.jpg)
Hi, here is the original image, the command line option is "2 2 400"

**Comment by nagadomi** [comment]
This is probably a model side issue. CUNet uses Global Average Pooling, so it may cause problems at block border, and the output pixels depends on the blocksize.
I have confirmed that there is no problem with benchmarks of only 2x and small block size (input size = 104 or 128).
If this problem occurs, overlapping tile process is probably useful.

**Comment by tanyiok1234** [comment]
> 
> 
> This is probably a model side issue. CUNet uses Global Average Pooling, so it may cause problems at block border, and the output pixels depends on the blocksize.
> I have confirmed that there is no problem with benchmarks of only 2x and small block size (input size = 104 or 128).
> If this problem occurs, overlapping tile process is probably useful.

Comfirmed that no above mentioned issues with input size = 128 (2x with any noise option [although low denoise generates strange results]). 
Maybe it is because the error is less than one pixel? Anyway, that's a good news.

**Comment by nihui** [comment]
It could be a bug at some resolution. As it could not been reproduced in the latest code.

**Comment by tanyiok1234** [comment]
Thanks, I think it is time to close this issue because I haven't reproduce it for a long time.
