### ISSUE TITLE
The webp output is not working.

### ISSUE THREAD

**Issue by Kafu-Ren** [nihui/waifu2x-ncnn-vulkan#101]
When output png, there is no problem, but if you modify it to webp, the webp will not be output.
Is this a bug? Or am I mistaken?

Use version is 20200818.

**Comment by kattjevfel** [comment]
What exact command are you executing?
If you use `waifu2x-ncnn-vulkan -i image.png -o image.webp` it will output webp, and ignore `-f`

As I understand it `-f webp` is only to be used when processing a directory.
Both work for me, using 20200818.

**Comment by Kafu-Ren** [comment]
I use cmd `waifu2x-ncnn-vulkan -i img.webp(or png) -o img.webp -n 0 -s 2 -j 2:2:2 -f webp`. 

'-f' was included and excluded, but only png and jpg worked normally, and webp did not output and input.)

The cmd log output is as follows:
[0 Geforce RTX 2060]    queueC=2[8]    queueG=0[16]    queueT=1[2]
[0 Geforce RTX 2060]    bugsbn1=0    buglbia=0     bugcopc=0    bigihfa=0
[0 Geforce RTX 2060]    fp16p=1    fp16s=1    fp16a=1    int8s=1    int8a=1

I tried reinstalling Vulkan runtime, but it's no use.

**Comment by kattjevfel** [comment]
Perhaps you haven't built libwebp support? I'm not sure how the program behaves without it. I've tried with it both as a submodule and using it from system (though it was always installed in the system anyways) and both work.
Also please use `-v` to see if you can perhaps get any more useful output.

```
katt@main ~/Desktop » waifu2x-ncnn-vulkan -i input.webp -o output.webp -v
WARNING: Experimental compiler backend enabled. Here be dragons! Incorrect rendering, GPU hangs and/or resets are likely
[0 AMD RADV/ACO VEGA10 (LLVM 10.0.1)]  queueC=1[4]  queueG=0[1]  queueT=0[1]
[0 AMD RADV/ACO VEGA10 (LLVM 10.0.1)]  bugsbn1=0  buglbia=0  bugcopc=0  bugihfa=0
[0 AMD RADV/ACO VEGA10 (LLVM 10.0.1)]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
[1 Radeon RX Vega]  queueC=1[4]  queueG=0[1]  queueT=2[2]
[1 Radeon RX Vega]  bugsbn1=0  buglbia=0  bugcopc=0  bugihfa=0
[1 Radeon RX Vega]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
input.webp -> output.webp done
katt@main ~/Desktop » file *
input.webp:  RIFF (little-endian) data, Web/P image
output.webp: RIFF (little-endian) data, Web/P image
```

**Comment by Kafu-Ren** [comment]
libwebp? I didn't hear that the library was needed. Is there a way to install this in Windows?

**Comment by kattjevfel** [comment]
It should build it for you if if you have the submodule in order.
https://github.com/nihui/waifu2x-ncnn-vulkan/blob/8b5c1cdfcde4b6da5127d60b11a1242ddc65bbb8/src/CMakeLists.txt#L226-L249

**Comment by Kafu-Ren** [comment]
I don't know about source code. but succeeded in getting libwebp for Windows. Currently, we have put libwebp in the waifu2x-ncn-vulkan folder and the configuration file path is waifu2x-ncn-vulkan\libwebp\bin. 

Download from libwebp for Windows:  https://developers.google.com/speed/webp/download

**Comment by Kafu-Ren** [comment]
I put the libwebp source code for Windows and libwebp source code in the waifu2x-ncnn-vulkan path respectively, but it still doesn't work.
Is this only available on Linux?

**Comment by Kafu-Ren** [comment]
I put the libwebp source code for Windows or libwebp source code in the waifu2x-ncnn-vulkan path respectively, but it still doesn't work.
Is this only available on linux?

**Comment by nihui** [comment]
try the prebuild binary https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20200818

**Comment by Kafu-Ren** [comment]
I don't know what prebuild binaries mean.
Even if that means source code, I don't know how to use it.

**Comment by nihui** [comment]
download waifu2x-ncnn-vulkan-20200818-windows.zip from project release page and unzip it, you will get the executable that supports webp on windows out of box

**Comment by Kafu-Ren** [comment]
In that exe file, png and jpg work, but only webp is not working.

**Comment by Kafu-Ren** [comment]
I checked again and the webp is working properly.

**Comment by Kafu-Ren** [comment]
I found the cause.  That is, the webp codec I used was libwebp_anim.  After processing the webp codec with libwebp in ffmpeg, it works normally.
