### ISSUE TITLE
_wfopen error on windows

### ISSUE THREAD

**Issue by poly000** [nihui/waifu2x-ncnn-vulkan#112]
```
D:\Program\waifu2x-ncnn-vulkan-20200818-windows>.\waifu2x-ncnn-vulkan.exe -s 1 -v -m models-upconv_7_anime_style_art_rgb -n 3 -i D:\SteamLibrary\steamapps\workshop\content\672870\09494\ot -o D:\SteamLibrary\steamapps\workshop\content\672870\09494\otw
[0 GeForce GTX 1050 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 GeForce GTX 1050 Ti]  bugsbn1=0  buglbia=0  bugcopc=0  bugihfa=0
[0 GeForce GTX 1050 Ti]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
_wfopen D:\Program\waifu2x-ncnn-vulkan-20200818-windows\models-upconv_7_anime_style_art_rgb/noise3_model.param failed
```

**Comment by poly000** [comment]
I noticed ` D:\Program\waifu2x-ncnn-vulkan-20200818-windows\models-upconv_7_anime_style_art_rgb`__/__`noise3_model.param`
should be `D:\Program\waifu2x-ncnn-vulkan-20200818-windows\models-upconv_7_anime_style_art_rgb`__\\__`noise3_model.param`

**Comment by ThatsNiceGuy** [comment]
can confirm, the application tries using the wrong path type as if it were on a unix based OS but this is windows

**Comment by ccicnce113424** [comment]
src/main.cpp
![image](https://user-images.githubusercontent.com/30774232/111870912-4e954c00-89c2-11eb-9ea8-e48ade4e96e7.png)

Clearly, the wrong printf controller was used for wchar_t array.
Replace %s with %ls and recompile to fix this problem.
