### ISSUE TITLE
Intent to package: Snaps are universal Linux packages

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [nihui/waifu2x-ncnn-vulkan#12]
Dear maintainer(s), 

[Snaps are universal Linux packages](https://snapcraft.io) that can be installed and run on many GNU+Linux distributions with ease.  I've been following the [Snapcrafters](https://forum.snapcraft.io/t/join-snapcrafters/1325) instructions and [have built a snap on the Snap Store](https://snapcraft.io/waifu2x-ncnn-vulkan), you may try it by running the following commands after [installing snapd](https://docs.snapcraft.io/installing-snapd/6735):
 
    # snap install --channel=edge waifu2x-ncnn-vulkan

This snap ships intel and AMD Vulkan drivers and _should_ be usable on supported hardware, unfortunately the GPU I'm using(Intel® HD Graphics 4600) doesn't have complete Vulkan driver and while it allows the application to launch properly it produces garbled images like the following one(`waifu2x-ncnn-vulkan 0.jpg 2.png 0 1 100`):

![](https://user-images.githubusercontent.com/13408130/56504414-073e8080-654b-11e9-8842-643e8ac0f958.png)

I'm also looking forward to working with you to make the packaging work upstream (if you're interested).  You may want to check out the current [packaging recipe](https://github.com/Lin-Buo-Ren/waifu2x-ncnn-vulkan-snap/blob/master/snap/snapcraft.yaml), the [documentation](https://docs.snapcraft.io), registering a developer account on the [Snap Store](https://snapcraft.io/store), and [get in touch with us](https://forum.snapcraft.io) to transfer the work under your control.

Thanks for your time and attention.

**Comment by Lin-Buo-Ren** [comment]
I got a new laptop with a Whiskey Lake gen.  intel GPU and the snap works perfectly:

![screenshot](https://user-images.githubusercontent.com/13408130/57582161-dfac5980-74f3-11e9-8124-c3b7971217d0.png)

**Comment by Nova-Aurora** [comment]
Can this be updated to reflect the last year of contribs?

**Comment by nihui** [comment]
Pre-build binary package for Linux is provided along with Windows and MacOS ones
You can download it from github release or CI artifact
