### ISSUE TITLE
Only CPU

### ISSUE THREAD

**Issue by talha0324** [nihui/waifu2x-ncnn-vulkan#127]
How to run it only on cpu? I need to run it on an environment of no gpu

**Comment by AffSeda** [comment]
I don't think it can work like that unless there is a valid Vulkan device implementation for your CPU installed on the system. Do you mean with Lavapipe or some such?

**Comment by talha0324** [comment]
okay I'm really new to this, everything works fine for me on PC.
I need to shift my code to a cloud VM (no gpu) when I run it, gives an error 
```
vkEnumeratePhysicalDevices failed -3
invalid gpu device
```
What do you suggest?

**Comment by AffSeda** [comment]
Okay, well first off I'm just a user (like you), so this is based on what I know which may or may not be the final answer.

That said, this software requires a Vulkan device. If you don't have a Vulkan device in the system, it won't work - hence the GPU requirement.

There is a Mesa project that provides Vulkan on CPU in Mesa 20.3 ([read about it here](https://www.phoronix.com/scan.php?page=news_item&px=Mesa-Vulkan-Lavapipe)) but I'm not sure it's complete enough to actually run this yet. My attempts to do so have not been successful.

**Comment by talha0324** [comment]
Thanks for this, will look into this!

**Comment by nihui** [comment]
https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20210102

support Apple M1
support running on cpu, which can be panellized with gpu, via -g -1
