### ISSUE TITLE
One-line help unclear

### ISSUE THREAD

**Issue by Artoria2e5** [nihui/waifu2x-ncnn-vulkan#13]
The current one-line help format with `[scale=1/2]` tends to make users (dumb me) type `scale=2` instead of `2` for that value. This... should probably be changed.

**Comment by nihui** [comment]
pull request is welcome :)

**Comment by nihui** [comment]
```
waifu2x-ncnn-vulkan -h
```

**Comment by Artoria2e5** [comment]
GETOPT YES
