### ISSUE TITLE
Low hardware request

### ISSUE THREAD

**Issue by happyeggchen** [nihui/waifu2x-ncnn-vulkan#133]
My computer only got 4gb RAM,and when I dealing with pics on my Linux laptop...it stucked and start fill up all my laptop's RAM and swap , but can't produce a pic

waifu2x-ncnn-vulkan -i sn.jpeg -o op.png -n 2 -s 2

(Sn.jpeg - 1000*1200 about)

Only happens when I want to deal with big pics...

**Comment by Tsubajashi** [comment]
Does your gpu support Vulkan? Sounds to me like it tries to work it out on your cpu, and therefore fills up your ram.

**Comment by happyeggchen** [comment]
> Does your gpu support Vulkan? Sounds to me like it tries to work it out on your cpu, and therefore fills up your ram.

it's geforce 610m...seemed like that it doesn't support vulkan

**Comment by happyeggchen** [comment]
Btw... I found that original waifu2x may could run in limited memory
![Screenshot_20210131-135912087.jpg](https://user-images.githubusercontent.com/38799701/106376059-80c7fb80-63cc-11eb-8b99-ba8a3f534c91.jpg)

**Comment by Tsubajashi** [comment]
Using a mobile version, with a pretty new Android you can safely assume that this device can use Vulkan.

**Comment by happyeggchen** [comment]
Ok,I'm using optirun in front of waifu2x
, -g auto after it now,but it showed up invalid gpu device
Why this happened? my  Nvidia-smi info


Sun Jan 31 20:44:14 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.138                Driver Version: 390.138                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 610M        Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   56C    P0    N/A /  N/A |      5MiB /  1985MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+

**Comment by Tsubajashi** [comment]
Again, if your gpu does not support Vulkan, it won't work on the gpu.

**Comment by happyeggchen** [comment]
So that means I have to get a vulkan driver for my gpu so that I could run it?Is that right?

**Comment by Tsubajashi** [comment]
Yes. :)

**Comment by nihui** [comment]
fixed in https://github.com/nihui/waifu2x-ncnn-vulkan/commit/086e73a59cdc84d285caebe9260385251cf0ec3a
