### ISSUE TITLE
使用2倍以上的放大倍率将导致软件滞留在后台无响应

### ISSUE THREAD

**Issue by AaronFeng753** [nihui/waifu2x-ncnn-vulkan#137]
软件版本: 20210210

经测试, 尽管20210210新增加了2倍以上的倍率支持, 但是当使用这些倍率时会导致软件滞留在后台, 既没有输出图片也没有正常退出.

操作系统:Windows10 专业版 20H2
配置: i7-8550u, AMD RX550 2GB, 16gb内存
参数: -s 4 -n 0 -t 128 -j 1:1:1 (如果手动放大相同图片两次, 不会崩溃可以正常输出, 所以不是内存或者显存不足, 之前的版本也都可以正常使用)

PS: 进程滞留在后台是通过 process lasso 发现的, Windows任务管理器看不到

**Comment by linser233** [comment]
#139 看看？
