### ISSUE TITLE
2 feature requests

### ISSUE THREAD

**Issue by lextra2** [nihui/waifu2x-ncnn-vulkan#14]
I'd like 2 features to be added, which I think should be fairly simple to implement:

1: the ability to log how much time, in MS, was spent to upscale an image. perhaps create a log file if `-log` was entered as an additional command.

2: the ability to specify which gpu to use if multiple gpus are installed. perhaps add something like `-gpu 0` `-gpu 1` etc. as an optional command to target a specific gpu.

**Comment by nihui** [comment]
gpu device can be selected via -g option now

the logging feature is not very important I think, so it is not implemented. you can always measure it with linux time or measure-command on windows
