### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by timsu92** [nihui/waifu2x-ncnn-vulkan#140]
- program version: 20210210(https://github.com/nihui/waifu2x-ncnn-vulkan/commit/77534d94b562148d07767c5c647a6a8b26013e2e)
- windows 20H2
- intel UHD Graphics 620  driver version: 27.20.100.9168
- nVidia GTX 1050 2GB   driver version: 27.21.14.6172 in task manager and 461.72 in nVidia Geforce experience

#### After seeing other issues, I've checked that...
- ...if I use GPU 0, the dedicated GPU RAM was occupied only roughly 0.5 GB
- ...if I use GPU 1, shared GPU RAM was occupied 1.4 GB while the total is 3.9 GB
- ...it didn't run and close immediately. The time was different between hardware.
- ...I'm using full path name as showing below.

### Command Lines:
- waifu2x-ncnn-vulkan.exe -i "D:\Documents\temp\video2x-test-pic\extracted_2146.jpg" -o "D:\Documents\temp\video2x-test-pic-out\2146.jpg" -n 3 -s 4 **-g -1 -j 1:4:1** -f jpg -v
- waifu2x-ncnn-vulkan.exe -i "D:\Documents\temp\video2x-test-pic\extracted_2146.jpg" -o "D:\Documents\temp\video2x-test-pic-out\2146.jpg" -n 3 -s 4 **-g 0 -j 1:2:1** -f jpg -v
- waifu2x-ncnn-vulkan.exe -i "D:\Documents\temp\video2x-test-pic\extracted_2146.jpg" -o "D:\Documents\temp\video2x-test-pic-out\2146.jpg" -n 3 -s 4 **-g 1 -j 1:1:1** -f jpg -v
### Screenshot
![未命名 - 3](https://user-images.githubusercontent.com/33785401/109493840-08865000-7ac8-11eb-9dc4-506cbb261462.jpg)

**Comment by timsu92** [comment]
Sorry! Duplicate of #138

**Comment by Kafu-Yukimura** [comment]
The issue has been successfully fixed.
Use build [20210521](https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20210521).

**Comment by timsu92** [comment]
Ok, I'll try it. Thanks for notifying me!

**Comment by timsu92** [comment]
Yes, it's fixed. Thanks @nihui , @utybo and @ArchieMeng !
