### ISSUE TITLE
png alpha channel loss

### ISSUE THREAD

**Issue by Kaens** [nihui/waifu2x-ncnn-vulkan#144]
Hi,
I found a bug where the alpha channel is lost.
Using waifu2x-ncnn-vulkan-20210210-windows on an RTX 2070.
The command-line switch is just "-n -1" or "-n 0".

Before: ![225986290](https://user-images.githubusercontent.com/5721423/112535534-78cd7c00-8dbd-11eb-9d7e-76ae867696a0.png)

After: ![225986290@2x](https://user-images.githubusercontent.com/5721423/112535537-79661280-8dbd-11eb-8747-bac7336f24e3.png)

**Comment by Kafu-Yukimura** [comment]
The bit value of the image is strange. (It is marked as 8bit in Windows properties. It must be marked in 32bit.)
Use'-pix_fmt rgba' in ffmpeg or save it through a separate image editing program.

**Comment by CounterContradiction** [comment]
@Kafu-Yukimura  is right.   

I have a similar image where it showed that it is 8bit if viewed through Windows Properties(Right Click-> Properties), and it also losses its transparency when using waifu2x-vulkan. 
![image](https://user-images.githubusercontent.com/82311894/124299388-5c16b200-db2b-11eb-818a-45ffb02b037a.png)
 
I saved the image as bear.png and run it through ffmpeg with the suggested command:
    `.\ffmpeg.exe -i .\bear.png -pix_fmt rgba bear_ff.png` 
And it ran without losing its transparency (-s 2 -n 2):
![bear_ff2x](https://user-images.githubusercontent.com/82311894/124299985-0c84b600-db2c-11eb-9f37-3ea0a99ac81a.png)


An altenative I found is with python and the Pillow library:
```
from PIL import Image
img = Image.open("bear.png")

#Checks if img is 8bit
if img.mode == "L" or img.mode == "P":
    #Converts to 32 bit and overwrites the original image. 
    #Use a different filename from the original if you want to preserve the original image.
    img.convert("RGBA").save("bear.png")  
```

**Comment by nihui** [comment]
fixed in https://github.com/nihui/waifu2x-ncnn-vulkan/commit/7ab564a955c23bcfbdabfe093a1791f5a761cb32
