### ISSUE TITLE
[Q] Does this work with the internal Intel GPUs on Macbooks?

### ISSUE THREAD

**Issue by NightMachinary** [nihui/waifu2x-ncnn-vulkan#146]
Does this work with the internal Intel GPUs on Macbooks?

It segfaults for me unless I specify =-g -1=:
```
❯ command waifu2x-ncnn-vulkan -g 0 -m '/Users/evar/Base/Software/- Resident/waifu2x-ncnn-vulkan-20210210-macos/models-cunet' -i '/Users/evar/Documents/Mangas/ultimate rockpaper/Manga/Ultimate Rock-Paper-Scissors/vol_001-English' -o '/Users/evar/Documents/Mangas/ultimate rockpaper/Manga/Ultimate Rock-Paper-Scissors/vol_001-English/enhanced' -f png


[0 Intel(R) Iris(TM) Graphics 550]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) Iris(TM) Graphics 550]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) Iris(TM) Graphics 550]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) Iris(TM) Graphics 550]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1]    22201 segmentation fault  command waifu2x-ncnn-vulkan -g 0 -m  -i  -o  -f png
```

**Comment by AffSeda** [comment]
I also segfault on an iMac Late 2015 (Iris Pro 6200). I think something changed in Big Sur, as it worked before a software update.

**Comment by zijianjiao2017** [comment]
![image](https://user-images.githubusercontent.com/61231083/116996884-aa1b5f00-ad0e-11eb-87d3-a9c9a412fc81.png)
![image](https://user-images.githubusercontent.com/61231083/116997021-d33bef80-ad0e-11eb-9411-bc6c4ba51321.png)

**Comment by zijianjiao2017** [comment]
````text
vkCreateInstance failed -9
````
![image](https://user-images.githubusercontent.com/61231083/116997126-fa92bc80-ad0e-11eb-9cdf-03af3490ea8e.png)

**Comment by zijianjiao2017** [comment]
So it is not possible or sth?😔

**Comment by zijianjiao2017** [comment]
> ```
> vkCreateInstance failed -9
> ```
> 
> ![image](https://user-images.githubusercontent.com/61231083/116997126-fa92bc80-ad0e-11eb-9cdf-03af3490ea8e.png)

Btw this error was printed in *ncnn*'s logic
![image](https://user-images.githubusercontent.com/61231083/116997893-ffa43b80-ad0f-11eb-83fe-872cee3fbdbe.png)
![image](https://user-images.githubusercontent.com/61231083/116997936-0df25780-ad10-11eb-876f-6a97aaf30b4d.png)

**Comment by NightMachinary** [comment]
@zijianjiao2017 It doesn’t work in Big Sur either.

**Comment by zijianjiao2017** [comment]
> @zijianjiao2017 It doesn’t work in Big Sur either.

Sed 😔

**Comment by nihui** [comment]
this is a known issue of ncnn inference library
and it has been fixed recently
will upgrade the internal ncnn source once another newer ncnn release comes

thanks for your report ！

**Comment by zijianjiao2017** [comment]
> this is a known issue of ncnn inference library
> and it has been fixed recently
> will upgrade the internal ncnn source once another newer ncnn release comes
> 
> thanks for your report ！

Nice 👍🏼

**Comment by nihui** [comment]
fixed in https://github.com/nihui/waifu2x-ncnn-vulkan/commit/784268f4c9ef112e8353328708893447ec54de7c
