### ISSUE TITLE
How to excute in Linux?

### ISSUE THREAD

**Issue by Excelsiorly** [nihui/waifu2x-ncnn-vulkan#147]
Hi, I've downloaded the Linux version:```waifu2x-ncnn-vulkan-20210210-ubuntu.zip```. But I didn't find out how to excute the file ```waifu2x-ncnn-vulkan```. It will be nice of you to anwser. Thanks!

**Comment by Nova-Aurora** [comment]
Extract the zip file into a folder, then enter into a terminal, navigate to the folder, and execute by running the command `./waifu2x-ncnn-vulkan [options]`

**Comment by Nova-Aurora** [comment]
You may need to set waifu2x-ncnn-vulkan as executable in your file manager or though the terminal first

**Comment by Excelsiorly** [comment]
thanks, i can run it on cpu now. However, when i tried to run it on the gpus, another error occured: 
```vkEnumeratePhysicalDevices failed -3
invalid gpu device```
my gpu informations are as followed:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   40C    P0    55W / 300W |   3945MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:89:00.0 Off |                    0 |
| N/A   73C    P0   173W / 300W |   3740MiB / 32510MiB |     61%      Default |
+-------------------------------+----------------------+----------------------+

```
looking forward to your reply!

**Comment by Provissy** [comment]
Please try to use `vulkaninfo` to check your vulkan status.
