### ISSUE TITLE
request: add .webp support

### ISSUE THREAD

**Issue by lextra2** [nihui/waifu2x-ncnn-vulkan#15]
Support for the .webp format would be a very welcome addition.
https://ffmpeg.org/ffmpeg-codecs.html#libwebp
Perhaps let us specify the compression level and quality aswell if the output file format would be .webp too.

**Comment by StarSparkleNova** [comment]
Second this

**Comment by Nova-Aurora** [comment]
Third this, but nihui seems to want this to be simple, at the cost of customization.

**Comment by Nova-Aurora** [comment]
As I said on #66, waifu2x-ncnn-vulkan uses stb for image coding on linux and macos, which only supports JPG, PNG, TGA, BMP, PSD, GIF, HDR, PIC for decoding and PNG, TGA, BMP for coding. So one would need to add another image decoder for webp support.

**Comment by nihui** [comment]
webp decoding support added since https://github.com/nihui/waifu2x-ncnn-vulkan/commit/adb3d868da74cbf033586be2b099e3dcf9f0ed2f

**Comment by nihui** [comment]
webp ebcoding support added since
https://github.com/nihui/waifu2x-ncnn-vulkan/commit/b68664991643f924f9678b5d4bfb542a4efd76ad
