### ISSUE TITLE
Linux (Ubuntu) - qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by peepopoggers** [nihui/waifu2x-ncnn-vulkan#157]
[Using this version](https://github.com/akai-katto/dandere2x/tree/521dc2d19d361b6f914c752cf6e71ffa623bde1f)

After running the bash script, and commands [here
](https://www.reddit.com/r/Dandere2x/comments/i9xn56/linux_rerelease_other_announcements/) (which by the way is missing a cd ./src), when I run:

`(venv) > $ python3 ./main.py`
It returns:

```
QObject::moveToThread: Current thread (0x1a3df50) is not the object's thread (0x1906cf0).
Cannot move to target thread (0x1a3df50)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/mnt/mydrive//upscale/dandere2x/venv/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```
[The guy here had the same issue but there was no public response](https://www.reddit.com/r/Dandere2x/comments/i9xn56/linux_rerelease_other_announcements/gj4kj5m?utm_source=share&utm_medium=web2x&context=3)

What could be the cause of this problem?

**Comment by peepopoggers** [comment]
I tried the install again, git cloned, navved to src, then ran bash script, then venv, source and pip, then main. Still no luck.

**Comment by Nova-Aurora** [comment]
Are you sure this is the right project? Waifu2x-ncnn-vulkan isn't Dandere2x. It doesn't call qt or python.

**Comment by peepopoggers** [comment]
wait wtf why am i here
