### ISSUE TITLE
System crash when using large block sizes

### ISSUE THREAD

**Issue by sat3ll** [nihui/waifu2x-ncnn-vulkan#16]
When attempting to use _blocksize = 1600_ (or higher values) and a large input image (2000x2000 +), this can freeze the entire system/crash the display driver requiring a hard reset (kernel logs recorded going out of VRAM).
Does the program perform some type of check to prevent using more VRAM than available (or soft capping to a safe value) ?

Note: Using reasonable blocksizes (default _= 400_) does not result in a crash.

**System**: Fedora 30 Linux
**GPU**: AMD Fury X (4GB VRAM)

**Comment by nihui** [comment]
The tilesize setting is now varied automatically according to the current gpu heap budget
with the default tilesize=0
