### ISSUE TITLE
No image output and broken on AMD Adrenalin 22.5.2

### ISSUE THREAD

**Issue by sabihoshi** [nihui/waifu2x-ncnn-vulkan#178]
[AMD Adrenalin 22.5.2](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-5-2) brings in additional [Vulkan extensions](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-vulkan) and that might've broken it.

In some weird way, it still works if I enable TTA and it outputs an image, but with it disabled, it seems to "succeed" but has no image output and no errors, the reason I think it is working fine is because it takes some time to process instead of failing immediately.

Is there some workaround for this? The only workaround I have for now is downgrading back to 22.5.1. Maybe it's not the fault of the project either but AMD, and could be fixed next update, but just submitting an issue in here just in case.

**Comment by denny466** [comment]
oh cool im not alone! same issue with pro driver 22.q2
except it returns 3221226356
not sure if video2x as gui front end matters

**Comment by denny466** [comment]
can confirm that TTA works on both waifu and realsr. i have no clue what that is but thanks for the temporary fix!

**Comment by sabihoshi** [comment]
> can confirm that TTA works on both waifu and realsr. i have no clue what that is but thanks for the temporary fix!

TTA averages outputs by upscaling it 8 times in different angles, which means it's 8x slower, so while it may be a fix, it's not really an ideal one. Read more about it in [here](https://github.com/nagadomi/waifu2x/issues/148#issuecomment-255754265)

**Comment by sabihoshi** [comment]
This issue has been fixed with 22.6.1 WHQL drivers.
