### ISSUE TITLE
Weirdly colored blocky output with nvidia

### ISSUE THREAD

**Issue by Toasterbirb** [nihui/waifu2x-ncnn-vulkan#180]
I'll let the output image explain the problem

Original
![lain](https://user-images.githubusercontent.com/48382422/178743024-c142bf5e-4038-42eb-af06-669876804b6d.png)

Upscaled with `waifu2x-ncnn-vulkan -g 0 -i lain.png -o upscaled.png`
![upscaled](https://user-images.githubusercontent.com/48382422/178743106-dbbb3065-fede-43c2-8d4c-9573b0a1d211.png)

I also have an AMD iGPU and that works fine. When using the nvidia gpu though, the output appears blocky and weirdly colored.

GPU in question: NVIDIA GeForce RTX 3060
Driver version: 515.57
CUDA Version: 11.7
Kernel: 5.18.11-gentoo
waifu2x-ncnn-vulkan version: 20220419 (latest one from the gentoo repos)

**Comment by vincent-hugot** [comment]
I have similarly bizarre output on an Arch-based system when using the package waifu2x-ncnn-vulkan 20220728-1, but **not** when using the executable waifu2x-ncnn-vulkan-20220728-ubuntu downloaded from this git, on the same input file. 

```
Kernel: 5.18.14-arch1-1 arch: x86_64 bits: 64
Distro: EndeavourOS
12-core AMD Ryzen 9 5900X 
NVIDIA GA104 [GeForce RTX 3070 Lite Hash Rate] driver: nvidia v: 515.57
```

**Comment by nihui** [comment]
I've confirmed that there is a computational bug on nvidia graphics cards and released a new version of ncnn today that fixes it.

https://github.com/Tencent/ncnn/releases/tag/20220729

Should be resolved when the archlinux package is updated

sorry for the annoyance

**Comment by Toasterbirb** [comment]
Can confirm that its fixed. Thanks for your efforts :+1:
