### ISSUE TITLE
simple performance test

### ISSUE THREAD

**Issue by nihui** [nihui/waifu2x-ncnn-vulkan#19]
A really large portion of the consumed time is for the vulkan runtime initialization

The real processing includes three parts, load png + waifu2x inference + save png

For small-size images, it is under 10% of the total time.

For large-size images, it is around 50% of the total time.

If the vulkan runtime and waifu2x instance can be reused for all the images, we can archive great speedup !

Yeah, 2x ~ 10x times faster !

![waifu2x 200x200 to 400x400](https://user-images.githubusercontent.com/171016/60399023-6c3cd500-9b91-11e9-88a4-a806ea07413a.png)

![waifu2x 1000x1000 to 2000x2000](https://user-images.githubusercontent.com/171016/60399026-71018900-9b91-11e9-981b-fc90a33c9f56.png)

**Comment by aka-katto** [comment]
From my understanding, this means in the future we could do bulk-upscaling (i.e upscaling a folder)?

I'm looking into using this for my waifu2x-derived project as it is much faster, but at the moment it has to re-initialize for each image. It would be a no-brainer in adopting this as a waifu2x-fork to use for my project.

**Comment by nihui** [comment]
yeah, I've planned to make the -i/-o option accept a folder path ;)

**Comment by nihui** [comment]
hi, I bring you the news of my very rough implementation :)

I may finish refactoring and polishing my code this weekend or sometime next week.

stay tuned ~

### tilesize=200 input=200x200 noise=2 scale=2

|cunet|one-by-one|batch|
|---|---|---|
|avg time(s) / image|0.86|0.0567|

|uprgb|one-by-one|batch|
|---|---|---|
|avg time(s) / image|0.75|0.0214|

### tilesize=200 input=1000x1000 noise=2 scale=2

|cunet|one-by-one|batch|
|---|---|---|
|avg time(s) / image|2.26|1.28|

|uprgb|one-by-one|batch|
|---|---|---|
|avg time(s) / image|1.41|0.44|

**Comment by nihui** [comment]
https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20190712
just posted a new waifu2x-ncnn-vulkan release, please let me know if you encounter problems
