### ISSUE TITLE
denoise=2 gives nosier results than 1 and 0

### ISSUE THREAD

**Issue by fireattack** [nihui/waifu2x-ncnn-vulkan#2]
Raw
![raw](https://user-images.githubusercontent.com/4130991/55655711-834e6f80-57ba-11e9-8b6b-1f09784e7bdf.jpg)

-1
![_-1](https://user-images.githubusercontent.com/4130991/55655722-88abba00-57ba-11e9-8614-09e9d7d36280.png)
0
![0](https://user-images.githubusercontent.com/4130991/55655723-88abba00-57ba-11e9-9518-e65d2934e886.png)
1
![1](https://user-images.githubusercontent.com/4130991/55655719-88132380-57ba-11e9-907a-c24f1bd751b3.png)
2
![2](https://user-images.githubusercontent.com/4130991/55655720-88132380-57ba-11e9-8141-b56c945b59cf.png)
3
![3](https://user-images.githubusercontent.com/4130991/55655721-88132380-57ba-11e9-897d-621978eb93ba.png)

Is this just an outlier?

**Comment by nihui** [comment]
the cunet model is the same one in waifu2x-caffe project
you can try upscale this image with the caffe converter and see if it is same with my tool
the result image shall be visually same.
