### ISSUE TITLE
Extra options request

### ISSUE THREAD

**Issue by sat3ll** [nihui/waifu2x-ncnn-vulkan#20]
- Is it possible to allow scale to be an arbitrary number or a multiple of 2? Currently we're locked to either 1 or 2.
- [DONE] ~~Is it possible to specify a directory containing images as input and have it output the images into another directory? This comes useful when converting many images at once. (waifu2x_caffe and waifu2x_converter_cpp have this behavior.) Currently, if I want to upscale 200 images I have to launch waifu2x-ncnn-vulkan 200 times! Launching it only once should improve performance greatly.~~

**Comment by nihui** [comment]
https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20190712
batch upscaling is implemented in the latest waifu2x-ncnn-vulkan release

**Comment by MrBridgeSix** [comment]
Batch upscaling does not scan subfolders within a folder and output files are renamed to .png.png .jpg.jpg and etc...

**Comment by AaronFeng753** [comment]
> Batch upscaling does not scan subfolders within a folder and output files are renamed to .png.png .jpg.jpg and etc...

You can try my waifu2x-extension ( Based on waifu2x-ncnn-vulkan (version 20190712) and Waifu2x-converter )
 https://github.com/AaronFeng753/Waifu2x-Extension

**Comment by nihui** [comment]
move to https://github.com/nihui/waifu2x-ncnn-vulkan/issues/9
