### ISSUE TITLE
能否提供一个iOS或者Android的demo呢？

### ISSUE THREAD

**Issue by fanyuecheng** [nihui/waifu2x-ncnn-vulkan#202]
既然ncnn是针对移动平台优化的高性能神经网络推理框架，那waifu2x-ncnn-vulkan必然是可以在iOS或者Android上运用的，能否提供一个demo呢？

**Comment by nihui** [comment]
https://play.google.com/store/apps/details?id=pro.archiemeng.waifu2x&hl=en&gl=US

**Comment by nihui** [comment]
https://github.com/tumuyan/RealSR-NCNN-Android
