### ISSUE TITLE
[Request] JPG / BMP Output

### ISSUE THREAD

**Issue by aaaboypop** [nihui/waifu2x-ncnn-vulkan#24]
Output Format for **slow cpu?**

| EXT | Type | CPU Usage | File Size |
| --- | --- | --- | --- |
| JPG | Lossy | Low | Small |
| BMP | Lossless | Very Low | Large |

**Comment by nihui** [comment]
bmp is tooooo large, I don't think an old slow cpu machine can be equipped with a fast and huge storage.

jpg saves space, that makes sense :)

image decoding and encoding will be done in separated threads, so the slow speed of png encoding won't be so important in future releases.

**Comment by Shad0w1and** [comment]
having a jpg output will be much appreciated! currently, I have to use another program to batch convert the result pictures to jpg. this feature will save me a lot of time.

**Comment by nihui** [comment]
webp encoding support here
https://github.com/nihui/waifu2x-ncnn-vulkan/commit/b68664991643f924f9678b5d4bfb542a4efd76ad

**Comment by nihui** [comment]
jpg encoding support here
https://github.com/nihui/waifu2x-ncnn-vulkan/commit/59d7234cb265b1e07d19d6488c26ab6f4b2c943f
