### ISSUE TITLE
【漏洞】转换带有透明通道的图片时会出现问题，无法保留图片的透明度

### ISSUE THREAD

**Issue by yoonhakcher** [nihui/waifu2x-ncnn-vulkan#26]
如题。
![luna](https://user-images.githubusercontent.com/10570103/61098176-073e8480-a499-11e9-8875-b9769eb05ff2.png)
▲原图
![luna-o](https://user-images.githubusercontent.com/10570103/61098183-1291b000-a499-11e9-96df-e4c2021d7edc.png)
▲输出结果
![luna(CUnet)(scale)(x2 000000)](https://user-images.githubusercontent.com/10570103/61098422-e1fe4600-a499-11e9-954c-b973c68ff848.png)
▲使用隔壁caffe版无此问题。

**Comment by nihui** [comment]
因为暂时不支持 RGBA ...
以后有这个打算
但是会放在 batch upscaling 和 arbitary scale ratio 后面。。。
