### ISSUE TITLE
output batch filename

### ISSUE THREAD

**Issue by aaaboypop** [nihui/waifu2x-ncnn-vulkan#27]
`"waifu2x-ncnn-vulkan.exe" -i "F:\out\1\temp\1" -o "E:\out" -n 3 -s 2 -t 200 -m "...waifu2x-caffe\models-upconv_7_anime_style_art_rgb" -g 0`

![explorer_3drX86r3iD](https://user-images.githubusercontent.com/13348147/61169291-bd7f9800-a585-11e9-915c-9681b33f011d.png)

**Comment by nihui** [comment]
It is the intentional behavior to append ".png" suffix to output filename.

If the input directory contains both a.jpg and a.png, then one of the two output images will be lost without this step since they are the same name "a.png".

**Comment by aaaboypop** [comment]
my input folder only has .png
why?

**Comment by aaaboypop** [comment]
jpg is same
![explorer_ntukr0fcrX](https://user-images.githubusercontent.com/13348147/61169705-d9d20380-a58a-11e9-9f0d-e1683e030c8c.png)

**Comment by nihui** [comment]
Yes, all image filenames will be appended with another png suffix.

a.png -> a.png.png
a.jpg -> a.jpg.png

This ensures that, a conflict with the same filename could occuer under no circumstances
I think it's reasonable and not very complicated to handle actually.
