### ISSUE TITLE
[Enchancement] Adding TTA mode

### ISSUE THREAD

**Issue by baraa272** [nihui/waifu2x-ncnn-vulkan#28]
First of all thanks very much for this Excellent Fast program of waifu2x concept 
anyway, i would like to suggest adding TTA mode to clean up artifacts of original image AS included in waifu2x-caffe 
i tested out your program on very bad JPEG full of artifacts , but the results wasn't cleaned up properly even while setting denoise level on 3  although caffe actually cleaned up everything and produced such an excellent upscaled image but with more time (5 minutes) on the other hand 
I hope your program succeed in every result from now on
My Best Regards

**Comment by nihui** [comment]
tta mode implemented https://github.com/nihui/waifu2x-ncnn-vulkan/commit/6651aa5c8754066c149f0058192ebdc20217cab1
