### ISSUE TITLE
没有gpu可以运行吗

### ISSUE THREAD

**Issue by wuxiaolianggit** [nihui/waifu2x-ncnn-vulkan#31]
waifu2x-ncnn-vulkan.exe运行之后没有结果，也没有报错，是因为我在Windows上没有gpu的原因吗

**Comment by nihui** [comment]
try upgrading your graphics driver

*    Intel: https://downloadcenter.intel.com/product/80939/Graphics-Drivers
*    AMD: https://amd.com/en/support
*    NVIDIA: https://nvidia.com/Download/index.aspx
