### ISSUE TITLE
'vkAllocateMemory failed -2' occured but image still comes out

### ISSUE THREAD

**Issue by AaronFeng753** [nihui/waifu2x-ncnn-vulkan#32]
I upgrade my gpu driver to the newest, but this 'vkAllocateMemory failed -2' error still occured, but the scaled image still comes out. 
What's the meaning of this error??

**Comment by nihui** [comment]
what is your gpu model
try using smaller tile size, such as "-t 200"

**Comment by AaronFeng753** [comment]
> what is your gpu model
> try using smaller tile size, such as "-t 200"
Thank you ! now this error is disappeared.
My gpu moder is AMD RX 550.
By the way, I just made a batching process extension for this program, so waifu2x-ncnn-vulkan could  process all the images in one folder, without input all images one by one. Check it out, hope you like it.
https://github.com/AaronFeng753/Waifu2x-Batching-process-extension

**Comment by nihui** [comment]
hi, the latest release of waifu2x-ncnn-vulkan accepts folder path as input and output. thanks anyway
