### ISSUE TITLE
Could you port it to android?

### ISSUE THREAD

**Issue by onexuan** [nihui/waifu2x-ncnn-vulkan#40]
Could you port it to android?

**Comment by Efreak** [comment]
I'd be interested too. NVidia shield (tablet and TV both) might be good targets for GPU support, as I believe they both support vulkan.

**Comment by Gokou-Ruri** [comment]
> I'd be interested too. NVidia shield (tablet and TV both) might be good targets for GPU support, as I believe they both support vulkan.

Thank you, I am looking forward to the Android version!

**Comment by Mar2ck** [comment]
There are some builds here you can run in an app called Termux: https://github.com/tanyiok1234/waifu2x_srmd-ncnn-vulkan-termux-binary

![Screenshot_20200310-143703_Termux_1](https://user-images.githubusercontent.com/6759254/76323882-3255ce00-62dd-11ea-93d5-d39e2eb2ae02.png)

**Comment by eadmaster** [comment]
for using in native android apps i guess this is the best way:
https://github.com/soywiz/kaifu2x

**Comment by ArchieMeng** [comment]
I am on it, and will be released soon.

**Comment by nonetrix** [comment]
Any updates?

**Comment by gmagic10** [comment]
Can you release the source code?

> I am on it, and it will be released soon. ![Screenshot_20211013-162759_Waifu2x_ncnn](https://user-images.githubusercontent.com/12139431/137630872-6571096d-5934-406e-a9aa-50be656e1b61.png) ![Screenshot_20211013-162909_Waifu2x_ncnn](https://user-images.githubusercontent.com/12139431/137630881-5de032f5-ccbe-4ed7-8cb6-9637d15ed158.png)

**Comment by ArchieMeng** [comment]
> Can you release the source code?
> 
> > I am on it, and it will be released soon.

I can release the source code once the open source license is chosen.
The App itself is now released on Google Play at https://play.google.com/store/apps/details?id=pro.archiemeng.waifu2x .

**Comment by ArchieMeng** [comment]
> > Can you release the source code?
> > > I am on it, and it will be released soon.
> 
> ~I can release the source code once the open source license is chosen.~
> 
> Since some uneventful things happened to another similar app, the release of source code is doubted. https://v2ex.com/t/811123
> 
> The App itself is now released on Google Play at https://play.google.com/store/apps/details?id=pro.archiemeng.waifu2x .
> 
> Update: I can release the source code once the open source license is chosen and get non-free parts replaced.

Core binding is now published. https://github.com/ArchieMeng/ncnn-android-waifu2x-demo
