### ISSUE TITLE
无法打开应用程序

### ISSUE THREAD

**Issue by mingmengyuan** [nihui/waifu2x-ncnn-vulkan#45]
应用程序打不开，我的是AMDRX580蓝宝石显卡。

**Comment by mingmengyuan** [comment]
CPU是AMD2600
显卡是AMDRX580-8G
系统window10-1903

**Comment by kingofotaku** [comment]
这是一个命令行下的工具，你不会直接双击打开exe了吧

**Comment by mingmengyuan** [comment]
> 这是一个命令行下的工具，你不会直接双击打开的exe了吧

呃，是的，那怎么用。

**Comment by kingofotaku** [comment]
>``@echo off
SET /p inputPATH=输入路径：

if exist %inputPATH%\* (Goto DIR) else (Goto FILE)

:DIR
mkdir %inputPATH%-s2n0
waifu2x-ncnn-vulkan.exe -n 0 -t 230 -m models-cunet -i %inputPATH% -o %inputPATH%-s2n0
Exit /b
:FILE
waifu2x-ncnn-vulkan.exe -n 0 -t 230 -m models-cunet -i %inputPATH% -o %inputPATH%-s2n0.png


这是我写的bat脚本（虽然很简陋但是可以用）。你新建一个文本文档然后把这一段打进去保存，修改文件后缀为.bat，最后把它放到waifu2x-ncnn-vulkan的目录下（和exe一起）打开之后把文件或者文件夹拖进去就可以了

**Comment by kingofotaku** [comment]
如果想要自定义参数的话先读一下说明，如果实在看不懂的话凑合用吧。

**Comment by kingofotaku** [comment]
好吧 才看见你是a卡，a卡只能用cpu运行，我这个你可能用不上。

**Comment by mingmengyuan** [comment]
> 如果想要自定义参数的话先读一下说明，如果实在看不懂的话凑合用吧。

嗯，要看运行进度条怎么办。

**Comment by mingmengyuan** [comment]
> 如果想要自定义参数的话先读一下说明，如果实在看不懂的话凑合用吧。

还是不怎么会弄，拖入文件。然后回车，运行，程序就没了

**Comment by mingmengyuan** [comment]
[
![mmexport1565086755569](https://user-images.githubusercontent.com/50936666/64924595-03243f80-d819-11e9-93d1-fca98d2514d7.jpg)
](url)

**Comment by mingmengyuan** [comment]
我想弄这张。

**Comment by kingofotaku** [comment]
是马上就没了（类似闪退），还是过几秒钟没的？如果是后者可能就代表已经转换好了，你看看原文件目录下有没有新的文件

**Comment by kingofotaku** [comment]
如果是闪退的话你可以试试把脚本里的-t 230这个参数改小一点，比如说改成-t 150或者100，然后再试试看

**Comment by kingofotaku** [comment]
![64924595-03243f80-d819-11e9-93d1-fca98d2514d7 jpg-s2n1](https://user-images.githubusercontent.com/12953574/64937333-74e9a100-d88c-11e9-9468-56bbace11559.png)

帮你转了下

**Comment by nihui** [comment]
666666

**Comment by mingmengyuan** [comment]
> ![64924595-03243f80-d819-11e9-93d1-fca98d2514d7 jpg-s2n1](https://user-images.githubusercontent.com/12953574/64937333-74e9a100-d88c-11e9-9468-56bbace11559.png)
> 
> 帮你转了下

谢谢您

**Comment by mingmengyuan** [comment]
> 如果是闪退的话你可以试试把脚本里的-t 230这个参数改小一点，比如说改成-t 150要么100，然后再试试看

还是直接闪退的那种吧，放入文件回车后，就闪退，新建了一个mmexport1565086651034.jpg-s2n0文件名的空文件夹
