### ISSUE TITLE
Error: _wfopen ??? failed ← when call waifu2x outside exe folder

### ISSUE THREAD

**Issue by XCanG** [nihui/waifu2x-ncnn-vulkan#46]
Tried to run any image through waifu2x, but get this error:
```
>waifu2x-ncnn-vulkan -i i.jpg -o o.png -n 2 -s 2
[0 GeForce GTX 1060 6GB]  queueC=2[8]  queueT=1[2]  memU=4294967295  memDL=7  memHV=9
[0 GeForce GTX 1060 6GB]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
_wfopen ??? failed
```

Does I need any external requirements?

CPU: Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz
GPU: GeForce GTX 1060 6GB
NVIDIA Driver version: 436.02
OS: Windows 10.0.17134 x64

_**EDIT:**_ with help of **gnattu** I figured out, what I have that error if call waifu2x outside of exe folder (this folder in PATH variable), this issue only when console in different catalog, than `waifu2x-ncnn-vulkan.exe`.

**Comment by silenceyear** [comment]
me too

waifu2x-ncnn-vulkan -i ./src -o ./dst -s 2
[0 GeForce GTX 1060 6GB]  queueC=2[8]  queueT=1[2]  memU=4294967295  memDL=7  memHV=9
[0 GeForce GTX 1060 6GB]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
_wfopen ??? failed

GPU: GeForce GTX 1060 6GB
NVIDIA Driver version: 436.30

**Comment by TacoDeBoss** [comment]
I had a similar issue, but explicitly specifying the model directory with the -m flag fixed it. I'm getting garbled image outputs though.
My old issue:
```
fopen models-cunet/noise2_scale2.0x_model.param failed
fopen models-cunet/noise2_scale2.0x_model.bin failed
Segmentation fault

**Comment by XCanG** [comment]
Tried adding -m, but issue don't change. Commands are:
```
>waifu2x-ncnn-vulkan -i i.jpg -o o.png -n 2 -s 2 -m models-cunet
>waifu2x-ncnn-vulkan -i i.jpg -o o.png -n 2 -s 2 -m models-upconv_7_anime_style_art_rgb
```

**Comment by gnattu** [comment]
I encountered similar situation, and I fount that I have to cd to the path of the program to make it work under windows(Windows Server 2019 DC). And everything is fine under Linux.

**Comment by XCanG** [comment]
Wow, that really fix issue, it work for me if I call command in same folder with exe.

**Comment by symant233** [comment]
Same here, but I'd prefer call the .exe in another path, hope author could fix that soon... @nihui

**Comment by Idesmi** [comment]
This still happens to me, on Linux.
`fopen models-upconv_7_photo/noise1_scale2.0x_model.param failed`
`fopen models-upconv_7_photo/noise1_scale2.0x_model.bin failed`

When I cd in the directory containing models, instead, everything works.
This issue does not concern cunet's bins and params, which can be opened from anywhere.
I am using release 20200606.

**Comment by Banderi** [comment]
Can confirm this still happens in Windows on 20200606 as well.

**Comment by nihui** [comment]
try the latest artifact build in CI

**Comment by Banderi** [comment]
I tried the artifact from https://github.com/nihui/waifu2x-ncnn-vulkan/runs/909102954 and it seems to be working!
Here's the `windows-2019` build: https://github.com/nihui/waifu2x-ncnn-vulkan/suites/962691968/artifacts/12130511

**Comment by tannisroot** [comment]
Still an issue for me with latest master on Linux:
```
waifu2x-ncnn-vulkan -i '/home/alex/waifu2x/i' -o '/home/alex/waifu2x/o' -m models-upconv_7_photo
[0 GeForce GTX 1070]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 GeForce GTX 1070]  bugsbn1=0  buglbia=0  bugcopc=0  bugihfa=0
[0 GeForce GTX 1070]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
fopen /usr/bin/models-upconv_7_photo/noise0_scale2.0x_model.param failed
fopen /usr/bin/models-upconv_7_photo/noise0_scale2.0x_model.bin failed
find_blob_index_by_name Input1 failed
find_blob_index_by_name Eltwise4 failed
```
