### ISSUE TITLE
编译源码提示缺少 ncnnConfig.cmake&ncnn-config.cmake

### ISSUE THREAD

**Issue by AaronFeng753** [nihui/waifu2x-ncnn-vulkan#51]
如题,我尝试下载源码后使用cmake进行编译, 出现如下提示

--------------
CMake Error at CMakeLists.txt:68 (find_package):
  By not providing "Findncnn.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ncnn", but
  CMake did not find one.

  Could not find a package configuration file provided by "ncnn" with any of
  the following names:

    ncnnConfig.cmake
    ncnn-config.cmake

  Add the installation prefix of "ncnn" to CMAKE_PREFIX_PATH or set
  "ncnn_DIR" to a directory containing one of the above files.  If "ncnn"
  provides a separate development package or SDK, be sure it has been
  installed.

-----------

已经按照ncnn的安装教程"Build for Windows x64 using Visual Studio Community 2017"在Windows 10 x64环境下安装ncnn, 安装时也没有报错, 但是文件夹下的确也找不到ncnnConfig.cmake&ncnn-config.cmake, 请问是什么情况???

注: 已经修改了CMakeLists.txt第67行的路径,但是没有文件,所以改了也没有什么用的样子.....

**Comment by kalcohol** [comment]
your cmake version?
better(may should) greater than 3.12

**Comment by kalcohol** [comment]
pls use
cmake --version
conform the version in Native Tools Command Prompt for Visual studio

**Comment by AaronFeng753** [comment]
> pls use
> cmake --version
> conform the version in Native Tools Command Prompt for Visual studio

Thank you, I found out that this is because I haven't updated Visual studio for a long time
