### ISSUE TITLE
unable to launch

### ISSUE THREAD

**Issue by Michael18751** [nihui/waifu2x-ncnn-vulkan#53]
tried to launch it and it shows a command prompt for half a second then closes. Tried running as admin. Using latest nvidia drivers and supports vulkan #

**Comment by Michael18751** [comment]
I recorded my screen and here is the last frame before it closes
![image](https://user-images.githubusercontent.com/53535277/71495323-57c55680-281b-11ea-8dda-985ffafbc742.png)

**Comment by yoonhakcher** [comment]
Windows Key + R 👉 Type "cmd" 👉 Enter 👉 Type the path of exe file.

**Comment by f11894** [comment]
@Michael18751
If you are not familiar with the CLI, use the GUI.

YukihoAA/waifu2x_snowshell: Multilingual waifu2x GUI shell for windows x64
https://github.com/YukihoAA/waifu2x_snowshell

**Comment by Michael18751** [comment]
ok. Thanks!
