### ISSUE TITLE
TTA mode does not work properly when image resolution is odd

### ISSUE THREAD

**Issue by f11894** [nihui/waifu2x-ncnn-vulkan#57]
```original image```
![1_trim](https://user-images.githubusercontent.com/16046279/75111106-9c356d00-5679-11ea-886e-128f85151616.png)

```waifu2x-ncnn-vulkan.exe -i "C:\issue\1_trim.png" -o "C:\issue\1_trim_vulkan x2.png" -s 2 -n -1 -t 100 -m models-cunet```
![1_trim_vulkan x2](https://user-images.githubusercontent.com/16046279/75111113-aa838900-5679-11ea-84ed-f46c1268d422.png)

```waifu2x-ncnn-vulkan.exe -i "C:\issue\1_trim.png" -o "C:\issue\1_trim_vulkan_tta_x2.png" -s 2 -n -1 -t 100 -m models-cunet -x```
![1_trim_vulkan_tta_x2](https://user-images.githubusercontent.com/16046279/75111124-b7a07800-5679-11ea-9f9b-1c6642b86e70.png)

```waifu2x-caffe-cui.exe -i "C:\issue\1_trim.png" -t 1 --crop_size 128 -m scale --scale_ratio 2 --model_dir models\CUnet -p cpu -o "C:\issue\1_trim_caffe_tta_x2.png"```
![1_trim_caffe_tta_x2](https://user-images.githubusercontent.com/16046279/75111130-bec78600-5679-11ea-8d1e-1aee496905c7.png)

**Comment by nihui** [comment]
Thanks for your report !
