### ISSUE TITLE
[BUG?] Ramdon Wrong Blocks (Termux Android with ncnn-vulkan-armv8a-android 20200226 prebuild library)

### ISSUE THREAD

**Issue by tanyiok1234** [nihui/waifu2x-ncnn-vulkan#58]
I built the waifu2x-ncnn-vulkan in termux. The speed is impressive.

I built it with ncnn-vulkan-armv8a-android 20200226 prebuilt library and lastest glslang. The libvulkan.so comes from /system/lib64. Build process finished in termux.

The result is interesting:
Sometimes it works propoerly, but sometimes it gives result like this:

![图片](https://user-images.githubusercontent.com/11721926/75326356-cd9e7a80-58bd-11ea-9dc3-df1adc64226f.png)
![图片](https://user-images.githubusercontent.com/11721926/75326368-d1320180-58bd-11ea-9593-cfd9867a90ad.png)
![图片](https://user-images.githubusercontent.com/11721926/75326372-d42cf200-58bd-11ea-8017-31a32e006627.png)

It happens also most randomly, independ with input pictures and TTA config, but seems to be relavent with GPU pressure (it happens more frequently wiht high process count and large block size.), the location are also random.
BTW, relavence to model is untested yet.

Anyideas about this phenomenon? Or how to get some logs about it?

**Comment by nihui** [comment]
please provide your phone spec and android system version

**Comment by tanyiok1234** [comment]
Rog 2 with Android 9.0 Snapdragon 855+ 12G Ram

Vulkan info as following:
![Screenshot_20200226-213448105_1](https://user-images.githubusercontent.com/11721926/75345641-7362e100-58e0-11ea-84c6-6203d1613443.jpg)

**Comment by tanyiok1234** [comment]
> please provide your phone spec and android system version

Rog 2 with Android 9, 855+, 12G Ram

Vulkan info as following:
![Screenshot_20200226-213624864_1](https://user-images.githubusercontent.com/11721926/75345921-fd12ae80-58e0-11ea-987a-2a4384668d83.jpg)

**Comment by tanyiok1234** [comment]
[Update] Problem may be found: when the cell phone turn on/off the screen, wrong blocks will be generated.

By delaying the startup (to turn of the screen) and avoiding touching the cellphone last night, it works correctly on all 18 pictures with  (-t 64 -x -j 1:3:3) following (-t 128 -j 1:3:3).

Maybe Android did something to the driver when turn on/off screen.

Why it looks random is just because I turn on/off the screen randomly. Large block size make looks larger.

**Comment by nihui** [comment]
I am currently investigating a ncnn bug in flushing and invalidating non-coherent device memory.
This problem should be caused by it
Thanks for your report

**Comment by tanyiok1234** [comment]
Update on 2020/03/05 based on Lastest master branch:
If I didn't make some mistakes when I build the ncnn, then it seems like the problem still exists:
I designed two tests with ssh connect:
![图片](https://user-images.githubusercontent.com/11721926/75989112-054c9880-5f36-11ea-9f1f-520ba9666434.png)
The screen are compeletely turned off during the first run, the result is nice:
![图片](https://user-images.githubusercontent.com/11721926/75989274-53fa3280-5f36-11ea-9770-bafdc369f2db.png)
During the second run, I turn off/on the screen periodically:
![图片](https://user-images.githubusercontent.com/11721926/75989430-99b6fb00-5f36-11ea-8819-6ebab86411bc.png)

**Comment by Mar2ck** [comment]
Don't know if it helps but im using tanyiok's builds from [here](https://github.com/tanyiok1234/waifu2x_srmd-ncnn-vulkan-termux-binary) and i can't reproduce this issue. I've tried turning the screen on and off over and over while its processing but the image isn't affected. Oneplus 6T, Android 9, Adreno 630, 8gb Ram. https://imgur.com/a/WM8kh0T

**Comment by tanyiok1234** [comment]
> 
> 
> Don't know if it helps but im using tanyiok's builds from [here](https://github.com/tanyiok1234/waifu2x_srmd-ncnn-vulkan-termux-binary) and i can't reproduce this issue. I've tried turning the screen on and off over and over while its processing but the image isn't affected. Oneplus 6T, Android 9, Adreno 630, 8gb Ram. https://imgur.com/a/WM8kh0T

Interesting...

I just update my ROG 2 to Android Q. Now the driver version is 512.415.0, so the driver version is newer than your Oneplus. I also recomplied the program with the lastest Vulkan SDK, ncnn. But I have no difficulty to reproduce this BUG.

It may imple that this is a platform/OS/vendor specific problem. Maybe more feedback from different cellphone can make it clear.

**Comment by fluffyloopy** [comment]
It works fine on my Samsung Galaxy A50 too. 6GB RAM. Android 10. Mali-G72. Turned the screen off and on multiple times during processing.
