### ISSUE TITLE
missing color channels ?

### ISSUE THREAD

**Issue by FluffyDiscord** [nihui/waifu2x-ncnn-vulkan#59]
tried release version 20200224
cmd: run.exe -i .\input\2225654d7eac7d8b1706169d4bd75d3e_original.jpg -o .\output\test1.jpg -n 1 -s 2 -g 0
went from 
![2225654d7eac7d8b1706169d4bd75d3e_original](https://user-images.githubusercontent.com/10332247/75613216-756cb000-5b2b-11ea-8a88-68a2aca2b161.jpg)

to
![test1](https://user-images.githubusercontent.com/10332247/75613219-7a316400-5b2b-11ea-9b2e-10a5b4db2b8a.jpg)

windows 10 64x 1909
gpu: rx 5700 xt and rx 470 (both gpu same result)
driver: 20.2.2

**Comment by extrimexxx** [comment]
i have too , version 20200224 from "pre-compiled binary for windows 64bit" have this bug, but version 20200223 work fine. win 10 x64 1909, gtx1070, driver laters

**Comment by m4st3rP** [comment]
I have the same issue with the 5700 XT and the 20.2.2 driver.

**Comment by sat3ll** [comment]
Can't reproduce on Linux with Mesa 19.3.3 [version 20200224].  
This bug might be specific to Windows only.

**Comment by NodokaMurmevent** [comment]
same bug on windows 5700 XT and driver 20.2.1

**Comment by YarlBoro** [comment]
Vega 56, driver 20.2.2 - same problem

**Comment by f11894** [comment]
This issue might be caused by "net.opt.use_int8_storage".
https://github.com/Nlzy/vapoursynth-waifu2x-ncnn-vulkan/issues/1#issuecomment-591960319

Here is a binary with "net.opt.use_int8_storage" to false.
https://ci.appveyor.com/project/f11894/waifu2x-ncnn-vulkan/builds/31510642/artifacts
please check if the issue is solved.

**Comment by extrimexxx** [comment]
`net.opt.use_int8_storage=false` issue is **not** solved

**Comment by f11894** [comment]
Could you try this binary as well?
https://ci.appveyor.com/project/f11894/waifu2x-ncnn-vulkan/builds/31514244/artifacts

build with waifu2x-ncnn-vulkan [4b626f8](https://github.com/nihui/waifu2x-ncnn-vulkan/commit/4b626f8d4a1f8ce331aa4678d93d3628d9670361)
build with ncnn 20200223 [3621009](https://github.com/Tencent/ncnn/commit/362100936dff97bdcfbcc4a208b3d18c2235e85f)

**Comment by YarlBoro** [comment]
Version with Your fixes process images correctly, at least on my rig. Thank you, **f11894**!

> Could you try this binary as well?
> https://ci.appveyor.com/project/f11894/waifu2x-ncnn-vulkan/builds/31514244/artifacts
> 
> build with waifu2x-ncnn-vulkan [4b626f8](https://github.com/nihui/waifu2x-ncnn-vulkan/commit/4b626f8d4a1f8ce331aa4678d93d3628d9670361)
> build with ncnn 20200223 [3621009](https://github.com/Tencent/ncnn/commit/362100936dff97bdcfbcc4a208b3d18c2235e85f)

**Comment by extrimexxx** [comment]
> Could you try this binary as well?

issue is not solved

**Comment by m4st3rP** [comment]
I am not sure if I tested it correctly, I used version 20200224 as a base and replaced "waifu2x-ncnn-vulkan.exe" with the one from the new binary you posted and it didn't fix the issue on my system, which conists of: Windows 10 1909, AMD RX 5700 XT, Adrenalin 2020 Edition 20.2.2. I also tried the binary in the fp32 folder and the binary from the root folder with the fp32 folder in the program folder.

**Comment by nihui** [comment]
It seems to be an image decoding / encoding issue.
waifu2x-ncnn-vulkan use Windows Image Component for image decoding and encoding on Windows platform, while stb_image for others.

However, this issue can not be reproduced in my window 10 box atm.

**Comment by FluffyDiscord** [comment]
> It seems to be an image decoding / encoding issue.
> waifu2x-ncnn-vulkan use Windows Image Component for image decoding and encoding on Windows platform, while stb_image for others.
> 
> However, this issue can not be reproduced in my window 10 box atm.

Can't be ffmpeg used to decode the image?

**Comment by nihui** [comment]
build two version of binary for testing, with the latest ncnn and waifu2x-ncnn-vulkan code

one uses windows image component for image decoding and encoding
another one uses stb_image

please comment if any of them solves this issue

[waifu2x-ncnn-vulkan-20200412-stb.zip](https://github.com/nihui/waifu2x-ncnn-vulkan/files/4466632/waifu2x-ncnn-vulkan-20200412-stb.zip)

**Comment by axel578** [comment]
@nihui It is still green for me ( tested the two version ) and the ouput is still green

**Comment by nihui** [comment]
> @nihui It is still green for me ( tested the two version ) and the ouput is still green

Thanks for your reply
I have to investigate further  :(

**Comment by nihui** [comment]
Cannot reproduce here :(

Windows 10 1909 18363.720
nvidia driver 445.75

**Comment by m4st3rP** [comment]
The output is also still green with either binary on my machine:
GPU: AMD Radeon RX 5700 XT
Driver: 20.4.1
OS: Windows 10 1909 18363.720

**Comment by nihui** [comment]
https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20200414

A special binary is provided for some old and buggy driver.
I am not sure if this issue could be resolved, but have a try..

**Comment by extrimexxx** [comment]
releases/tag/20200414 green image GPU: gtx1070 Windows 10 1909 18363.752 Nvidia 445.75

**Comment by lextra2** [comment]
@nihui 
20200414 is still green with AMD GPUs

the last build that works is 20200223

**Comment by lextra2** [comment]
@nihui 
20200414 is still green with AMD GPUs
neither executable works
the last build that worked is 20200223

**Comment by m4st3rP** [comment]
I also have the same issue with both binaries.
GPU: AMD Radeon RX 5700 XT
Driver: 20.4.1
OS: Windows 10 1909 18363.720

**Comment by freigus** [comment]
I also have the same issue.
I did "a bit" of testing with different parameters.
Build: 20200414.
OS: Windows 10 1909 (18363.778).
Results were the same on GTX 1060 6GB (tried drivers: 441.87 and 445.87) and Intel HD 630.
Bug appeared in both normal and fp16p versions.
models-upconv_7_photo and models-upconv_7_anime_style_art_rgb made result picture in blue. models-cunet made result picture in green.
Intensity of color distortion varies depending on noise-level parameter, where -1 resulted in less distorted colors and 3 resulted in very distorted(cunet) or almost black(upconv) picture.
In testing I usually used -t 100 -j 1:1:1 parameters. Examples without them are marked with "no-t no-j" in name.
Examples are on [Google Drive](https://drive.google.com/open?id=1-eGI9N_oS8LadsmNsq2FoVXAcP4Hk6wM)
I'll try testing on another workstation (Intel HD 5300 and older Windows) later.
Also please tell me if I can help with testing this bug.

**Comment by ultrasn0w** [comment]
Updated to 20200414 today and having the same issue;
all tested images have a strong green tint.

Windows 10 1909 (18363.815)
NVIDIA RTX 2070 with Driver 445.87
Normal and FP16p executable

**Comment by freigus** [comment]
So, tested builds:
Bug appears on builds 20200414 and 20200224.
Builds 20200223 and before it don't have color distortion.

Problem is somewhere in those commits?

**Comment by nihui** [comment]
Here is a new snapshot release build with recently updated ncnn library
Please give it a try, Thank you.

The download link is at the artifact section
https://github.com/nihui/waifu2x-ncnn-vulkan/actions/runs/112581139

**Comment by m4st3rP** [comment]
Sadly the issues persists for me.
GPU: AMD Radeon RX 5700 XT
Driver: 20.4.1
OS: Windows 10 1909 18363.836

**Comment by extrimexxx** [comment]
green image
waifu2x-ncnn-vulkan.exe -i 2.jpg -o 2x.jpg
input:
![2](https://user-images.githubusercontent.com/33065618/82710436-4aae7580-9c9c-11ea-9c51-1e4e1cf7d0d1.jpg)
output:
![2x](https://user-images.githubusercontent.com/33065618/82710462-5c901880-9c9c-11ea-80b7-e923de01f223.jpg)

**Comment by christantoan** [comment]
Still having this problem with version 20200530

**Comment by Faniia** [comment]
https://github.com/k4yt3x/video2x/issues/254#issuecomment-639482430

**Comment by k4yt3x** [comment]
To summarize, @xyz00777 found that this bug will be triggered when the display language is German or some other non-English languages.

**Comment by christantoan** [comment]
Huh? But I'm using English

**Comment by f11894** [comment]
I've prepared a binary that reverts 2041d93 and 28207dd, so you can try it out.
https://ci.appveyor.com/project/f11894/waifu2x-ncnn-vulkan/builds/33341219/artifacts
https://github.com/f11894/waifu2x-ncnn-vulkan/tree/locale_revert

**Comment by christantoan** [comment]
I just tested further and I think it's because of region decimal symbol setting.

Original:
![illust_82084647_20200605_062417](https://user-images.githubusercontent.com/7300310/83888661-5c038180-a774-11ea-9dd2-5413974029ef.jpg)
Command line I used: `.\waifu2x-ncnn-vulkan.exe -i ".\illust_82084647_20200605_062417.jpg" -o ".\illust_82084647_20200605_062417vUSComma.jpg" -x` USComma can change based on the region setting
If I'm using my usual setting (English (Netherlands)), I got this:
![illust_82084647_20200605_062417vNL](https://user-images.githubusercontent.com/7300310/83888495-1777e600-a774-11ea-918c-5c02f0ae9104.jpg)
If I'm using English (United States):
![illust_82084647_20200605_062417vUS](https://user-images.githubusercontent.com/7300310/83888538-2e1e3d00-a774-11ea-9fed-edd2a77e6409.jpg)
If I'm using English (United States) but changed the decimal symbol to comma:
![illust_82084647_20200605_062417vUSComma](https://user-images.githubusercontent.com/7300310/83888608-4a21de80-a774-11ea-89dc-a94bb1fc4b55.jpg)

**Comment by christantoan** [comment]
> 
> 
> I've prepared a binary that reverts [2041d93](https://github.com/nihui/waifu2x-ncnn-vulkan/commit/2041d931af6b5a4de7f1e886355f37637da60e2d) and [28207dd](https://github.com/nihui/waifu2x-ncnn-vulkan/commit/28207dd60940797a93af8586ff4bb6a9efc9dc5e), so you can try it out.
> https://ci.appveyor.com/project/f11894/waifu2x-ncnn-vulkan/builds/33341219/artifacts
> https://github.com/f11894/waifu2x-ncnn-vulkan/tree/locale_revert
Ninja'd :(

I got `invalid outputpath extension type` error on both executables. I used the same command from the one I posted before.

**Comment by aleves** [comment]
@f11894 Works for me now with sv-SE (Swedish) locale.

@christantoan Try deleting all the ".\" behind the filenames except the executable. PowerShell is fun 🙃

**Comment by christantoan** [comment]
I AM STUPID!!!

I used .jpg as the output extension when it should be .png even when the program already said it.
Anyway, it works now with comma as decimal separator (EN-NL)

**Comment by lextra2** [comment]
Oh wow. Actually insane how **not** using English (United States) as Region format causes these graphical issues.

![321](https://user-images.githubusercontent.com/20690384/83893981-ffdb3600-a750-11ea-9628-75dbfae0cd57.PNG)

**Comment by christantoan** [comment]
@lextra2, you don't need to reboot or set the region to EN-US. Changing decimal symbol setting to period should be enough.
![image](https://user-images.githubusercontent.com/7300310/83894440-83118180-a77b-11ea-8209-426df2614832.png)

**Comment by lextra2** [comment]
@christantoan ohhh thats much better. thanks a lot!

**Comment by FluffyDiscord** [comment]
Not a fix but a workaround. How does language settings even affect script?

**Comment by christantoan** [comment]
Maybe parsing error or something? When it sees comma it thinks it's a decimal separator or vice versa.
I've seen it happens before with other software.

**Comment by nihui** [comment]
reproduced
will work out a fix in ncnn and push a new release
Thanks to all

**Comment by Nova-Aurora** [comment]
So this is an upstream issue?

**Comment by extrimexxx** [comment]
@nihui Work good for me in laters CI Artifacts. Thank You!

**Comment by nihui** [comment]
https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20200606
