### ISSUE TITLE
More options for scaling?

### ISSUE THREAD

**Issue by Nova-Aurora** [nihui/waifu2x-ncnn-vulkan#62]
Can I scale more than 2x using this upscaler? The software is excellent, but I wish I could upscale further.

**Comment by VoidxHoshi** [comment]
It seems that only 2 times magnification is artificially limited by the author, maybe you can try the following tools (based in part on this project).
https://github.com/AaronFeng753/Waifu2x-Extension-GUI

**Comment by Nova-Aurora** [comment]
I looked at the Cpp code and concur, but I run Linux and I don't think I can run your suggestion. Is there a way to patch this?

**Comment by VoidxHoshi** [comment]
> I looked at the Cpp code and concur, but I run Linux and I don't think I can run your suggestion. Is there a way to patch this?

For Linux, you can try another project of the same author (but it may not be as good as waifu2x for 2D anime images)
https://github.com/nihui/srmd-ncnn-vulkan

**Comment by Nova-Aurora** [comment]
Further looking at the code for this, if I remove the code that checks the scaling options, it still fails to scale, so this is something in the main algorithm, not just a artificial limitation.

**Comment by nihui** [comment]
duplicated of https://github.com/nihui/waifu2x-ncnn-vulkan/issues/9
