### ISSUE TITLE
invalid gpu device on GTX 1070 - i7 6700k

### ISSUE THREAD

**Issue by axel578** [nihui/waifu2x-ncnn-vulkan#65]
Hello, I encounter this error on my computer with a gtx 1070, i7 6700k with CUDA installed.

Command used ( default ) : waifu2x-ncnn-vulkan.exe -i 0003.png -o output.png -n 2 -s 2
FULL ERROR : 
vkEnumerateInstanceExtensionProperties failed -3
invalid gpu device

From the Code, I assume that it's because the GPU is not detected : 
int gpu_count = ncnn::get_gpu_count();

**Comment by nihui** [comment]
upgrade your GPU driver
https://www.nvidia.com/Download/index.aspx

**Comment by axel578** [comment]
![google](https://user-images.githubusercontent.com/44734791/79069988-c8ad5300-7cd2-11ea-80e0-13fee76a3623.png)
This is the result for 2x scale, it's all green, do you know why ?

**Comment by nihui** [comment]
move to https://github.com/nihui/waifu2x-ncnn-vulkan/issues/59
