### ISSUE TITLE
不能正常運行 waifu2x

### ISSUE THREAD

**Issue by uimee** [nihui/waifu2x-ncnn-vulkan#67]
顯卡資訊
![image](https://user-images.githubusercontent.com/18748818/79550916-8ff2ec80-80cb-11ea-995b-10970007c6f7.png)
驅動資訊
![image](https://user-images.githubusercontent.com/18748818/79551141-da746900-80cb-11ea-9561-2d0c875f5b34.png)
當我運行了這個指令`waifu2x-ncnn-vulkan.exe -i test.jpg -o output.png -n 2 -s 2`
![image](https://user-images.githubusercontent.com/18748818/79553473-1e1ca200-80cf-11ea-85c8-308d1ada71e6.png)
它只顯示了這個 但沒有出現任何新檔案

**Comment by kingofotaku** [comment]
只會一直保持圖中的樣子？還是會出現別的錯誤提示呢？

**Comment by Nova-Aurora** [comment]
kingofotaku in case something goes wrong. uimee, how large is the file you're converting? Normally it is just taking a long time to convert when it gives me that output.

**Comment by uimee** [comment]
> 只會一直保持圖中的樣子？還是會出現別的錯誤提示呢？

直接退出

**Comment by kingofotaku** [comment]
> > 只會一直保持圖中的樣子？還是會出現別的錯誤提示呢？
> 
> 直接退出
過程會持續多久？以及你確定你輸入的檔案路徑是正確的？建議試試輸入完整的檔案路徑。
