### ISSUE TITLE
windows下N卡，输出的图片放大倍率后变黑

### ISSUE THREAD

**Issue by ljm000** [nihui/waifu2x-ncnn-vulkan#7]
WIN10
GTX1050
Intel cpu

D:\waifu2x-ncnn-vulkan-20190408>waifu2x.exe  001.jpg n001.jpg 2 2
[0 GeForce GTX 1050]  queueC=2  queueT=1  memU=4294967295  memDL=7  memHV=9
[0 GeForce GTX 1050]  fp16s=1  fp16a=0  int8s=1  int8a=1

输出后，输出图片变黑

D:\waifu2x-ncnn-vulkan-20190408>waifu2x.exe  001.jpg n001.jpg 3 1
[0 GeForce GTX 1050]  queueC=2  queueT=1  memU=4294967295  memDL=7  memHV=9
[0 GeForce GTX 1050]  fp16s=1  fp16a=0  int8s=1  int8a=1

输出图片正常，但是倍率不能放大

**Comment by Dearmw** [comment]
> WIN10 
> GTX1050 
> 英特尔CPU
> 
> D：\ waifu2x-ncnn-vulkan-20190408> waifu2x.exe 001.jpg n001.jpg 2 2 
> [0 GeForce GTX 1050] queueC = 2 queueT = 1 memU = 4294967295 memDL = 7 memHV = 9 
> [0 GeForce GTX 1050] fp16s = 1 fp16a = 0 int8s = 1 int8a = 1
> 
> 输出后，输出图片变黑
> 
> D：\ waifu2x-ncnn-vulkan-20190408> waifu2x.exe 001.jpg n001.jpg 3 1 
> [0 GeForce GTX 1050] queueC = 2 queueT = 1 memU = 4294967295 memDL = 7 memHV = 9 
> [0 GeForce GTX 1050] fp16s = 1 fp16a = 0 int8s = 1 int8a = 1
> 
> 输出图片正常，但是倍率不能放大

同样的问题不过我是VEGA

**Comment by nihui** [comment]
也是这个问题吗？ https://github.com/nihui/waifu2x-ncnn-vulkan/issues/6

**Comment by Dearmw** [comment]
> 也是这个问题吗？[＃6](https://github.com/nihui/waifu2x-ncnn-vulkan/issues/6)

是啊。也是一样的问题 waifu2x.exe  2  2输出的文件变黑，1 1正常但是不能放大

**Comment by ljm000** [comment]
> 也是这个问题吗？ #6

是的，放大输出图片变黑

**Comment by nihui** [comment]
新版本已经基本完成了，明天我会再测试下打包上传新版本

**Comment by nihui** [comment]
20190413 已上传，新增blocksize可选参数用来减少显存使用，缩减单次提交的command数量以获得更好的系统响应

测试了以下几个没有问题
gtx1070 on windows 10
gtx1070 on fedora 29
gt940m on fedora 29
intel hd graphics 5500 on fedora 29
a10-7850k on windows 10 (block size = 200)

**Comment by nihui** [comment]
@ljm000 @Dearmw  请确认下新版是否还有这个问题 :P

**Comment by ljm000** [comment]
> @ljm000 @Dearmw 请确认下新版是否还有这个问题 :P

OK，问题解决
