### ISSUE TITLE
Build guide

### ISSUE THREAD

**Issue by Doomsdayrs** [nihui/waifu2x-ncnn-vulkan#72]
A build guide for linux would be very nice

**Comment by Provissy** [comment]
I struggle with building for a while but finally got it done. Here is a rough guide on building on Ubuntu Focal.

First build `ncnn` following this guide https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-linux-x86

Make sure you run `make install` after building `ncnn`, it seems that the recipe won't actually install them into your system. You need to run `export ncnn_DIR=/path-to-ncnn-build/install` to let CMake know where they are.

Then you can use tradition CMake style building techniques:
```
cd waifu2x-ncnn-vulkan/src
mkdir build && cd build
cmake ..
make
```

It seems that this project requires no extra dependencies, `g++ cmake protobuf vulkan`(as listed in their build guide) for `ncnn` seems enough.

There is a minor problem I encountered, `libprotobuf` from Ubuntu Focal seems not compatible with `ncnn`, in that case you need to add `-DNCNN_BUILD_TOOLS=OFF` as your CMake option for `ncnn`.

**Comment by Computious** [comment]
I have made it through this guide through trial and error ![Screenshot_2020-05-14_17-21-18](https://user-images.githubusercontent.com/65370370/81987313-e4d14680-9628-11ea-9092-074199e34715.png) but am stuck and would love help with these three questions.

What directory should I place the make build into?
How do I launch waifu2x-ncnn-vulkan after I have built it?

**Comment by Provissy** [comment]
> I have made it through this guide through trial and error 
> 
> How can I have waifu2x in its fully build form placed in /usr/local/ so that I do not have to have it messing with my workflow in downloads?
> How do I launch waifu2x-ncnn-vulkan after I have built it?
> What would the command for making a waifu2x-ncnn-vulkan desktop launcher look like?

To run the program, execute `./waifu2x-ncnn-vulkan` in the build directory.

To install it, copy the `waifu2x-ncnn-vulkan` file as well as its models (those directories starting with "models-") into `/usr/local/bin` directory. You can also place the models elsewhere, but in that case you should run `waifu2x-ncnn-vulkan` with models path specified.

Even if you are in a desktop environment, like gnome, you run it through a terminal. It is not an GUI app unless someone wraps it with an graphical interface.

**Comment by Computious** [comment]
Know that this is a CLI program, I would still like to create a launcher, I don't do a lot of work through CL and I would like to have a script that immediately navigates to the proper folder and launches waifu2x, a shoddy attempt pictured below.

![Screenshot_2020-05-14_20-44-37](https://user-images.githubusercontent.com/65370370/81999658-4f907b00-9645-11ea-9301-9871ef1b7bd6.png)

How do I make a shortcut that launches waifu2x in terminal?

**Comment by Doomsdayrs** [comment]
@Computious select run in terminal

**Comment by Computious** [comment]
@Doomsdayrs you would think but that does nothing.

**Comment by Computious** [comment]
using an AskUbuntu thread I reached this
![closer](https://user-images.githubusercontent.com/65370370/82095194-13652500-96ee-11ea-8e7c-76e6871653ad.png)
however when I attempt to run the launcher I am met with this
![error](https://user-images.githubusercontent.com/65370370/82095257-3ee80f80-96ee-11ea-8cf2-a864029b2a7f.png)
maybe this troubleshooting will help us make it the whole way.

**Comment by Computious** [comment]
Fixed it and learned a lesson in Mint/Ubuntu, compiling it and placing it in `/usr/local/bin` makes it a program that can be launcher from any location. therefore all I needed was the bash section.

![Screenshot_2020-05-16_23-58-54](https://user-images.githubusercontent.com/65370370/82135524-49d89800-97f3-11ea-843c-8e2ccfda9501.png)

I hope someone finds this useful if they come across it!

**Comment by nihui** [comment]
I added a small build note on README
https://github.com/nihui/waifu2x-ncnn-vulkan#build-from-source
