### ISSUE TITLE
Default tile size to big for gt1030

### ISSUE THREAD

**Issue by blue-devil-93** [nihui/waifu2x-ncnn-vulkan#73]
Hi,
First of all your application is  fast even on my  pc.
Do have an nvidia gt1030, ryzen3 1200 and asus b350 board. Not the most powerful hardware nowadays. However an image gets converted in less than 10 sec and that beats even waifu2x-converter-cpp in speed and quality.

I have to lower the tile to 34-200 if i do not do that the application produces black output. Also the green-/blue bug exists too. Downgrade fixes this issue tough.
System i tested on was win7 as i use this occassionally as an offline system for image processing.

Did see the sourcecode comes with cmake files. Is it buildable on linux? 
Use ububuntu as a main system. So that  i could try to determine which tilesize the gt1030  supports.

**Comment by Nova-Aurora** [comment]
It is buildable on linux (I have it built through the AUR on my manjaro system). I have no idea about anything else.

**Comment by blue-devil-93** [comment]
Got it running on linux runs even faster than on windows:
Here some hints what i did on ubuntu 18.04 to get it running. Sadly lack
the time to make a full instruction but you might find it helpful.

https://github.com/Tencent/ncnn/tree/af646b65774184aa9b6dda5b4459c543d8899eca

mkdir -p build
    cd build
cmake \
        -DCMAKE_TOOLCHAIN_FILE=../toolchains/host.gcc.toolchain.cmake \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DNCNN_BUILD_EXAMPLES=OFF \
        -DNCNN_BUILD_TOOLS=OFF \
        -DNCNN_VULKAN=ON \
        ..

sudo make DESTDIR="${pkgdir}" install



https://github.com/nihui/waifu2x-ncnn-vulkan
waifu2x-ncnn-vulkan-20190712

sed -i 's|path_t model = PATHSTR("models-cunet")|path_t model =
PATHSTR("/usr/share/waifu2x-ncnn-vulkan/models-cunet")|' main.cpp

cd src

mkdir -p build
    cd build
    cmake \
        -DCMAKE_INSTALL_PREFIX=/usr \
        ..
    make

//Note you might add the headers/files from ncnn to waifu2x-converter to
make it work

sudo  install -Dm755 "waifu2x-ncnn-vulkan" "/usr/bin/waifu2x-ncnn-vulkan"

for f in models-*/*; do
        install -Dm 644 "$f" ${pkgdir}/usr/share/waifu2x-ncnn-vulkan/"$f"
    done

**Comment by nihui** [comment]
The default tilesize setting is now respect the current gpu heap budget since
https://github.com/nihui/waifu2x-ncnn-vulkan/commit/a714e40f663ea99f3d1db2f5250febdc0a1a22a6

**Comment by nihui** [comment]
For the green-/blue bug, please try the latest build. Thanks
https://github.com/nihui/waifu2x-ncnn-vulkan/actions/runs/114565941
