### ISSUE TITLE
Conversion fails in ver 20190414.

### ISSUE THREAD

**Issue by f11894** [nihui/waifu2x-ncnn-vulkan#8]
Windows 10
Ryzen 2400G

waifu2x.exe "C:\waifu2x\test.png" "C:\waifu2x\test(CUnet)(noise_scale)(Level1)(x2).png" 1 2 200

[0 AMD Radeon(TM) RX Vega 11 Graphics]  queueC=1  queueT=2  memU=2  memDL=0  memHV=1
[0 AMD Radeon(TM) RX Vega 11 Graphics]  fp16s=1  fp16a=0  int8s=1  int8a=0
vkCreateShaderModule failed -3
local_shader_module 0000000000000000 waifu2x_preproc_int8s created

Conversion is successful in versions up to efd54ee.
efd54ee までのバージョンでは変換に成功します。

**Comment by nihui** [comment]
try upgrading your graphics driver
amd https://www.amd.com/en/support

**Comment by f11894** [comment]
After installing Adrenalin 2019 Edition 19.4.1, it now works properly.
Adrenalin 2019 Edition 19.4.1をインストールしたところ正常に動作するようになりました。
