### ISSUE TITLE
Duplicate file extension when using input/output directories

### ISSUE THREAD

**Issue by bajuwa** [nihui/waifu2x-ncnn-vulkan#81]
For an input image named `image.jpg` it will output `image.jpg.png`

**Comment by Nova-Aurora** [comment]
It will only output as png or webp. Try image.png

**Comment by Nova-Aurora** [comment]
Try downloading the latest version and try again.

**Comment by bajuwa** [comment]
This is using the latest version as of filing this ticket: version 20200606

**Comment by Nova-Aurora** [comment]
I'm not a C++ coder by trade, but it looks like, when using batch processing, the output filename and directory are determined just by essentially doing:
`(output directory)'+'/'+'(input file name)'+'(ouput file name)'` (lines 594-612 in main.cpp)
A fix would probably subtract the input file extension from the input file name before passing it to this operation.

**Comment by Nova-Aurora** [comment]
The code for the fixed version probably would look something like:
`extpos = get_file_extension(filenames[i])`
`output_file_name = filenames[i].erase(extpos - 1)'`
`output_files[i] = outputpath + PATHSTR('/') + output_file_name + PATHSTR('.')+ format;`
I can't get waifu2x-ncnn-vulkan to build to test it currently, and I don't code C++ so take this with a grain of salt

**Comment by Nova-Aurora** [comment]
@nihui could you take at look at this?

**Comment by nihui** [comment]
implemented in https://github.com/nihui/waifu2x-ncnn-vulkan/commit/80c810576194c6ecfa6909afbb5c0312da9679b3
