### ISSUE TITLE
20200606: cannot build with system-wide ncnn and libwebp

### ISSUE THREAD

**Issue by slashbeast** [nihui/waifu2x-ncnn-vulkan#82]
Hi,

It seems that version 20200606 can no longer be built with system-wide ncnn as it does look for ncnn locally in source tree and fails if it does not exist.

    if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/ncnn/CMakeLists.txt")
        message(FATAL_ERROR "The submodules were not downloaded! Please update submodules with \"git submodule update --init --recursive\" and try again.")
    endif()

Same goes for libwebp

    if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/libwebp/CMakeLists.txt")
        message(FATAL_ERROR "The submodules were not downloaded! Please update submodules with \"git submodule update --init --recursive\" and try again.")
    endif()

In Gentoo we uses https://github.com/nihui/waifu2x-ncnn-vulkan/archive/20200606.tar.gz as the source (from release page).

Can you please restore a way to not use bundled/submodule dependencies?

**Comment by slashbeast** [comment]
I've hacked CMakeLists.txt a bit but I do seems to crash on ncnn, is it possible that current release does not work with latest release of ncnn and require master branch of ncnn?

```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index abfdab2..596e9f1 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -83,10 +83,6 @@ else()
     message(WARNING "IPO is not supported: ${ipo_supported_output}")
 endif()
 
-# build ncnn library
-if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/ncnn/CMakeLists.txt")
-    message(FATAL_ERROR "The submodules were not downloaded! Please update submodules with \"git submodule update --init --recursive\" and try again.")
-endif()
 
 option(NCNN_INSTALL_SDK "" OFF)
 option(NCNN_PIXEL_ROTATE "" OFF)
@@ -174,12 +170,7 @@ option(WITH_LAYER_mish "" OFF)
 option(WITH_LAYER_statisticspooling "" OFF)
 option(WITH_LAYER_swish "" OFF)
 
-add_subdirectory(ncnn)
-
-# build libwebp library
-if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/libwebp/CMakeLists.txt")
-    message(FATAL_ERROR "The submodules were not downloaded! Please update submodules with \"git submodule update --init --recursive\" and try again.")
-endif()
+find_package(ncnn REQUIRED)
 
 option(WEBP_ENABLE_SIMD "" ON)
 option(WEBP_BUILD_ANIM_UTILS "" OFF)
@@ -195,8 +186,6 @@ option(WEBP_BUILD_WEBP_JS "" OFF)
 option(WEBP_NEAR_LOSSLESS "" OFF)
 option(WEBP_ENABLE_SWAP_16BIT_CSP "" OFF)
 
-add_subdirectory(libwebp)
-
 include_directories(${CMAKE_CURRENT_SOURCE_DIR}/libwebp/src)
 
 # look for vulkan compute shader and compile
```

The crash
```
[ 86%] Building CXX object CMakeFiles/waifu2x-ncnn-vulkan.dir/main.cpp.o
/home/piotr/src/waifu2x-ncnn-vulkan/src/main.cpp: In function ‘int main(int, char**)’:
/home/piotr/src/waifu2x-ncnn-vulkan/src/main.cpp:661:61: error: ‘class ncnn::VulkanDevice’ has no member named ‘get_heap_budget’
  661 |         uint32_t heap_budget = ncnn::get_gpu_device(gpuid)->get_heap_budget();
      |                                                             ^~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/waifu2x-ncnn-vulkan.dir/build.make:83: CMakeFiles/waifu2x-ncnn-vulkan.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/waifu2x-ncnn-vulkan.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

```

**Comment by nihui** [comment]
yeah, it currently depends on the ncnn git master code. That's why I setup ncnn as a submodule
I shall add a cmake option to enable using system ncnn and libwebp after a new ncnn release

**Comment by tanyiok1234** [comment]
That would be great, I also got some difficulties in compling libwebp as submodule in termux. But system libwebp is available.

**Comment by nihui** [comment]
ncnn-20200616 released

**Comment by nihui** [comment]
fixed in  https://github.com/nihui/waifu2x-ncnn-vulkan/commit/a2e592426bf06ef50a09a8aa99f6eca08b30b395

note: The code requires up-to-date ncnn to work properly.
