### ISSUE TITLE
Invalid gpu device

### ISSUE THREAD

**Issue by xXHenlolXx** [nihui/waifu2x-ncnn-vulkan#83]
![image](https://user-images.githubusercontent.com/27168630/84082051-8f811e80-a9b5-11ea-8f20-221da7445cbe.png)

I can't use waifu2x-ncnn-vulkan because of this error. It's weird because standard waifu2x is working normally.

My system:
CPU: Ryzen 7 3700x
GPU: GTX 1060 6GB
Ram: 16GB

Thanks in advance

**Comment by Nova-Aurora** [comment]
try using the flag -g 1 to switch to a different GPU device, but it should be defualting to the 1060.

**Comment by xXHenlolXx** [comment]
I tried, but it didn't work.

**Comment by xXHenlolXx** [comment]
Here I have some prints of what is happening.
![84189055-fe6c7f00-aa6a-11ea-8fce-243a3a9455a6](https://user-images.githubusercontent.com/27168630/84189269-64590680-aa6b-11ea-9c71-55550bc3d806.png)

I am using the latest drivers (v446.140) and in theory it should be gpu 0.
![84188850-a0d83280-aa6a-11ea-99b9-dfbbc883d567](https://user-images.githubusercontent.com/27168630/84189275-66bb6080-aa6b-11ea-9115-bffe78d3b404.png)

**Comment by xXHenlolXx** [comment]
I fixed it. All I needed to do was reinstall my video driver.
