### ISSUE TITLE
ubuntu16.04, fail to run it

### ISSUE THREAD

**Issue by splinter21** [nihui/waifu2x-ncnn-vulkan#85]
I installed vulkan by running "apt install vulkan-utils"

./waifu2x-ncnn-vulkan -i 10298469.jpg -o opt.png -n 3 -s 1 -j 4:4:4

Xlib:  extension "NV-GLX" missing on display "localhost:13.0".
vkEnumeratePhysicalDevices failed -3
invalid gpu device

my devices (and driver):

![111](https://user-images.githubusercontent.com/26759495/84511004-7dc2b280-acf8-11ea-946d-ddfe20d92f1c.png)

CUDA8

**Comment by splinter21** [comment]
I use XShell to run the cmd, why Xmanager opens?

**Comment by Kiyamou** [comment]
You need to update GPU driver

**Comment by splinter21** [comment]
> You need to update GPU driver

do you mean NVIDIA driver? what version should I install at least?

**Comment by Kiyamou** [comment]
> do you mean NVIDIA driver? what version should I install at least?

Yes, the NVIDIA driver 384.130 is old.
I don't know the exact version, but the latest version is always right.
You can get it from https://www.nvidia.com/Download/index.aspx
