### ISSUE TITLE
Fails with ACO (RADV_PERFTEST=aco)

### ISSUE THREAD

**Issue by AffSeda** [nihui/waifu2x-ncnn-vulkan#91]
As ACO is about to become default behavior on Mesa, I thought this worth mentioning - if ACO is enabled by either environment variable or globally, waifu2x-ncnn-vulkan doesn't seem to work. For example;

raven@Raven:~/.local/bin$ **./waifu2x-ncnn-vulkan -i fullbody1.png -o fullbody1-2x.png**
[0 AMD RADV NAVI10 (LLVM 10.0.0)]  queueC=1[4]  queueG=0[1]  queueT=0[1]
[0 AMD RADV NAVI10 (LLVM 10.0.0)]  buglssc=0  bugsbn1=0  buglbia=0  bugihfa=0
[0 AMD RADV NAVI10 (LLVM 10.0.0)]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1

raven@Raven:~/.local/bin$ **RADV_PERFTEST=aco ./waifu2x-ncnn-vulkan -i fullbody1.png -o fullbody1-2x-aco.png**
[0 AMD RADV/ACO NAVI10 (LLVM 10.0.0)]  queueC=1[4]  queueG=0[1]  queueT=0[1]
[0 AMD RADV/ACO NAVI10 (LLVM 10.0.0)]  buglssc=0  bugsbn1=0  buglbia=0  bugihfa=0
[0 AMD RADV/ACO NAVI10 (LLVM 10.0.0)]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
vec1 16 ssa_31 = mov ssa_29.xSegmentation fault

I have been able to reproduce the same behaviour on a Radeon VIII (Vega20), Radeon Vega64 (Vega10), and several other random amdgpu cards.

**Comment by Tremeschin** [comment]
Same with an RX 570 on Arch, running `mesa-tkg-git 20.2.0_devel.126263.912ad091125-1`, `lib32-mesa-tkg-git 20.2.0_devel.126263.912ad091125-1` packages from the Chaotic-AUR with `waifu2x-ncnn-vulkan 20200606-1` from the AUR, can run with `RADV_PERFTEST=llvm` but not `RADV_PERFTEST=aco`, same error, `vec1 16 ssa_31 = mov ssa_29.xSegmentation fault`

Other implementations of the ncnn from nihui doesn't work as well like the `srmd-ncnn-vulkan` and `realsr-ncnn-vulkan`.

**Comment by nihui** [comment]
Does the latest ci artifact work ? 
https://github.com/nihui/waifu2x-ncnn-vulkan/actions/runs/165404222

**Comment by nihui** [comment]
can not reproduce on my fedora 32 box
R9 M295X  mesa-20.1.3

If mesa-20.1.x ACO works, it may be a regression bug introduced in mesa-20.2 ACO

**Comment by AffSeda** [comment]
> Does the latest ci artifact work ?
> https://github.com/nihui/waifu2x-ncnn-vulkan/actions/runs/165404222

Yes, this works. I've tested it on all my systems, and it functions with aco now.

**Comment by AffSeda** [comment]
It's faster with ACO as well. Sometimes half the time. Thanks a lot for this software, it is really great.
