### ISSUE TITLE
Greyscale input images result in corrupted output on Linux in recent builds

### ISSUE THREAD

**Issue by awused** [nihui/waifu2x-ncnn-vulkan#94]
I haven't narrowed it down to a specific commit but version 20200414 works as expected while version 20200530 and later produce corrupted output when used on greyscale images. The output is distorted and different parts of the image are interleaved on top of each other.

I've only tested with PNG images using the cunet model. A working colour image can be converted with `convert colour.png -colorspace Gray grey.png`. Scaling factors and denoising levels don't seem to have any effect.

I've also tested the precompiled Windows and Linux binaries. The Windows 20200530 or 20200606 binaries are apparently unaffected by this bug but the Linux binaries are affected (on Fedora 32) with the same output.

When building 20200414 I was using the 20200413 version of ncnn.

![colour](https://user-images.githubusercontent.com/1551320/88624096-3ea7b100-d05b-11ea-8500-aa81bd753f88.png)
![grey](https://user-images.githubusercontent.com/1551320/88624110-45362880-d05b-11ea-892f-8c61d3fb099b.png)
![scale-1-denoise-1](https://user-images.githubusercontent.com/1551320/88624124-4bc4a000-d05b-11ea-8d7c-35f65fcec77c.png)

**Comment by nihui** [comment]
fixed. try the latest ci artifact

**Comment by awused** [comment]
The issue is fixed with that commit. Thanks.
