### ISSUE TITLE
Does not check exe directory for models

### ISSUE THREAD

**Issue by PazerOP** [nihui/waifu2x-ncnn-vulkan#95]
Using the Windows version. It's not possible to "install" the program somewhere, then add it to your path. If you try that, you get an error about `_wfopen` failing on one of the models.

```
C:\Users\matt\Downloads\test>waifu2x -s 2 -i image.png -o image_out.png
[0 GeForce RTX 2060]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 GeForce RTX 2060]  buglssc=0  bugsbn1=0  buglbia=0  bugihfa=0
[0 GeForce RTX 2060]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
_wfopen models-cunet/noise0_scale2.0x_model.param failed

C:\Users\matt\Downloads\test>where waifu2x
C:\Program Files\waifu2x-ncnn-vulkan-windows\waifu2x.exe
```

The program should check for these files in the exe directory to avoid this issue.

**Comment by nihui** [comment]
try the latest ci artifacts

**Comment by nihui** [comment]
fixed in https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20200818
