### ISSUE TITLE
Output .jpg missing/removed?

### ISSUE THREAD

**Issue by WalkerMx** [nihui/waifu2x-ncnn-vulkan#96]
As per the docs "  -f format            output image format (jpg/png/webp, default=ext/png)"

Actually setting options to jpg however, or just trying to output a jpg fails with error "invalid outputpath extension type".

Was jpg output removed, or is this a bug?

**Comment by nihui** [comment]
It's a new feature of the coming new version
try the latest ci artifact

**Comment by WalkerMx** [comment]
Aye. Thanks ^^
